---
document: feedback-pipeline-repository
version: 2
data:
  name: Standard Automotive repositories based on C9S
  description: >
    C9S Repositories for Base Autopackages (BaseOS, AppStream,
    PowerTools, CBS AutoSD packages, CBS Automotive packages,
    Neptune)
  # Contacts: psabata, ssmoogen
  maintainer: automotive-base-enablement
  source:
    repos:
      cbs-autosd:
        baseurl: https://buildlogs.centos.org/9-stream/autosd/$basearch/packages-main/
        priority: 0
      cbs-automotive:
        baseurl: https://buildlogs.centos.org/9-stream/automotive/$basearch/packages-main/
        priority: 50
      stream-baseos:
        baseurl: https://composes.stream.centos.org/production/latest-CentOS-Stream/compose/BaseOS/$basearch/os/
        priority: 100
      stream-appstream:
        baseurl: https://composes.stream.centos.org/production/latest-CentOS-Stream/compose/AppStream/$basearch/os/
        priority: 100
      stream-powertools:
        baseurl: https://composes.stream.centos.org/production/latest-CentOS-Stream/compose/CRB/$basearch/os/
        priority: 100
      neptune:
        baseurl: https://download.copr.fedorainfracloud.org/results/pingou/qtappmanager-fedora/centos-stream-9-$basearch/
        priority: 500
    releasever: "9"
    composeinfo: https://composes.stream.centos.org/production/latest-CentOS-Stream/compose/metadata/composeinfo.json
    # Automotive is only focusing on a subset of architectures
    architectures:
      - aarch64
      - x86_64
