---
# This configuration file defines an "Environment" in Feedback Pipeline.
# https://tiny.distro.builders
#
# Environments influence how a workload looks like when installed.
# That's achieved by including specific packages — like coreutils-single — that
# influence the result.
# Environments can also act as base images when monitoring container sizes.

document: feedback-pipeline-environment
version: 1
data:
  # id is the filename — that automatically prevents collisions for free!


  ### MANDATORY FIELDS ###
  
  # Name is an identifier for humans
  #
  # (mandatory field)
  name: CentOS Stream 8 minimal microdnf env.
  
  # A short description, perhaps hinting the purpose
  #
  # (mandatory field)
  description: Minimal env. for CentOS Stream microdnf

  # Who maintains it? This is just a freeform string
  # for humans to read. In Fedora, a FAS nick is recommended.
  #
  # (mandatory field)
  maintainer: james

  # Different instances of the environment, one per repository.
  #
  # (mandatory field)
  repositories:
  - repository-c8s

  # Packages defining this environment.
  # This list includes packages for all
  # architectures — that's the one to use by default.
  #
  # (mandatory field)
  packages:
  - microdnf
  - glibc-minimal-langpack
  - coreutils-single

  # Labels connect things together.
  # Workloads get installed in environments with the same label.
  # They also get included in views with the same label.
  # 
  # (mandatory field)
  labels:
  - centos


  ### OPTIONAL FIELDS ###

  # Architecture-specific packages.
  #
  # (optional field)
  #arch_packages:
  #  x86_64:
  #  - arch-specific-package

  # Extra installation options.
  # The following are now supported:
  # - "include-docs" - include documentation packages
  # - "include-weak-deps" - automatically pull in "recommends" weak dependencies
  #
  # (optional field)
  #options:
  #- option

