document: feedback-pipeline-workload
version: 1
data:
  name: CEE support tools
  description: Support tools used by customers and Support Delivery
  maintainer: sst_cee_supportability

  packages:
  - sos
  - rig

  labels:
  - eln
  - c9s

  package_placeholders:
    support-tools-container:
      description: This package ships in RHEL as a support tool, but does not ship in Fedora. 
