document: feedback-pipeline-workload
version: 1
data:
  name: meta-sig packages
  description: ELN Extras packages that Meta cares about
  maintainer: meta-sig

  packages:
  - atop
  - awscli
  - azure-cli
  - btrd
  - btrfs-progs
  - ccache
  - compsize
  - ctags
  - dbench
  - drgn
  - duo_unix
  - duo_unix-selinux
  - et
  - htop
  - iotools
  - fping
  - libbtrfs
  - libbtrfsutil
  - libkdumpfile-devel
  - mkosi
  - mosh
  - msr-tools
  - neovim
  - netconsd
  - ngrep
  - packetdrill
  - packetdrill-data
  - pam_duo
  - pngquant
  - python3-btrfsutil
  - python3-pystemd
  - python3-testslide
  - qrencode-devel
  - ripgrep
  - screen
  - sdparm
  - sedutil
  - stress
  - stressapptest
  - strongswan
  - tpm-tools

  labels:
  - eln-extras
