document: feedback-pipeline-workload
version: 1
data:
  name: kde eln-extra packages
  description: KDE Plasma Desktop ELN Extras packages
  maintainer: tdawson

  packages:
  - analitza
  - ark
  - ark-libs
  - artikulate
  - artikulate-libs
  - baloo-widgets
  - blinken
  - bluedevil
  - bomber
  - bovo
  - breeze-cursor-theme
  - breeze-icon-theme
  - breeze-icon-theme-rcc
  - cervisia
  - colord-kde
  - digikam
  - digikam-libs
  - dolphin
  - dolphin-libs
  - dolphin-plugins
  - dragon
  - extra-cmake-modules
  - filelight
  - granatier
  - gwenview
  - gwenview-libs
  - java-kolabformat
  - juk
  - kaccounts-integration
  - kactivitymanagerd
  - kamera
  - kamoso
  - kanagram
  - kapman
  - kapptemplate
  - kate
  - kate-plugins
  - katomic
  - kbackup
  - kblackbox
  - kblocks
  - kbounce
  - kbruch
  - kcachegrind
  - kcachegrind-converters
  - kcalc
  - kcharselect
  - kcm_systemd
  - kcolorchooser
  - kcolorpicker
  - kcron
  - kdb
  - kdb-driver-mysql
  - kdb-driver-postgresql
  - kdebugsettings
  - kde-cli-tools
  - kde-connect
  - kdeconnectd
  - kde-connect-libs
  - kde-connect-nautilus
  - kdecoration
  - kde-dev-scripts
  - kde-dev-utils
  - kde-dev-utils-common
  - kdeedu-data
  - kde-filesystem
  - kdegraphics-mobipocket
  - kdegraphics-thumbnailers
  - kde-gtk-config
  - kde-partitionmanager
  - kdeplasma-addons
  - kde-print-manager
  - kde-print-manager-libs
  - kdesdk-kioslaves
  - kdesdk-thumbnailers
  - kde-settings
  - kde-settings-plasma
  - kde-settings-pulseaudio
  - kdesu
  - kdf
  - kdiagram
  - kdialog
  - kdiamond
  - kdnssd
  - keditbookmarks
  - keditbookmarks-libs
  - kexi
  - kexi-libs
  - kf5-akonadi-mime
  - kf5-akonadi-notes
  - kf5-akonadi-search
  - kf5-akonadi-server
  - kf5-akonadi-server-mysql
  - kf5-attica
  - kf5-audiocd-kio
  - kf5-baloo
  - kf5-baloo-file
  - kf5-baloo-libs
  - kf5-bluez-qt
  - kf5-filesystem
  - kf5-frameworkintegration
  - kf5-frameworkintegration-libs
  - kf5-grantleetheme
  - kf5-kactivities
  - kf5-kactivities-stats
  - kf5-kalarmcal
  - kf5-kapidox
  - kf5-karchive
  - kf5-kauth
  - kf5-kblog
  - kf5-kbookmarks
  - kf5-kcalendarcore
  - kf5-kcalendarutils
  - kf5-kcmutils
  - kf5-kcodecs
  - kf5-kcompletion
  - kf5-kconfig
  - kf5-kconfig-core
  - kf5-kconfig-gui
  - kf5-kconfigwidgets
  - kf5-kcontacts
  - kf5-kcoreaddons
  - kf5-kcrash
  - kf5-kdav
  - kf5-kdbusaddons
  - kf5-kdeclarative
  - kf5-kded
  - kf5-kdelibs4support
  - kf5-kdelibs4support-libs
  - kf5-kdesignerplugin
  - kf5-kdesu
  - kf5-kdewebkit
  - kf5-kdnssd
  - kf5-kdoctools
  - kf5-kemoticons
  - kf5-kfilemetadata
  - kf5-kglobalaccel
  - kf5-kglobalaccel-libs
  - kf5-kguiaddons
  - kf5-kholidays
  - kf5-khtml
  - kf5-ki18n
  - kf5-kiconthemes
  - kf5-kidentitymanagement
  - kf5-kidletime
  - kf5-kimageformats
  - kf5-kimap
  - kf5-kinit
  - kf5-kio
  - kf5-kio-core
  - kf5-kio-core-libs
  - kf5-kio-file-widgets
  - kf5-kio-gui
  - kf5-kio-ntlm
  - kf5-kio-widgets
  - kf5-kio-widgets-libs
  - kf5-kipi-plugins
  - kf5-kipi-plugins-libs
  - kf5-kirigami
  - kf5-kirigami2
  - kf5-kirigami2-addons
  - kf5-kitemmodels
  - kf5-kitemviews
  - kf5-kitinerary
  - kf5-kjobwidgets
  - kf5-kjs
  - kf5-kjsembed
  - kf5-kldap
  - kf5-kmbox
  - kf5-kmediaplayer
  - kf5-kmime
  - kf5-knewstuff
  - kf5-knotifications
  - kf5-knotifyconfig
  - kf5-kontactinterface
  - kf5-kpackage
  - kf5-kparts
  - kf5-kpeople
  - kf5-kpimtextedit
  - kf5-kpkpass
  - kf5-kplotting
  - kf5-kpty
  - kf5-kquickcharts
  - kf5-kross
  - kf5-kross-core
  - kf5-kross-ruby
  - kf5-kross-ui
  - kf5-krunner
  - kf5-kservice
  - kf5-ksmtp
  - kf5-ktexteditor
  - kf5-ktextwidgets
  - kf5-ktnef
  - kf5-kunitconversion
  - kf5-kwallet
  - kf5-kwallet-libs
  - kf5-kwayland
  - kf5-kwidgetsaddons
  - kf5-kwindowsystem
  - kf5-kxmlgui
  - kf5-kxmlrpcclient
  - kf5-libkcddb
  - kf5-libkcompactdisc
  - kf5-libkdcraw
  - kf5-libkexiv2
  - kf5-libkgeomap
  - kf5-libkipi
  - kf5-libkleo
  - kf5-libksane
  - kf5-libktorrent
  - kf5-modemmanager-qt
  - kf5-networkmanager-qt
  - kf5-plasma
  - kf5-prison
  - kf5-purpose
  - kf5-rpm-macros
  - kf5-solid
  - kf5-sonnet
  - kf5-sonnet-core
  - kf5-sonnet-ui
  - kf5-syndication
  - kf5-syntax-highlighting
  - kf5-threadweaver
  - kfind
  - kfloppy
  - kfourinline
  - kgeography
  - kgoldrunner
  - khangman
  - khelpcenter
  - khotkeys
  - kig
  - kigo
  - kile
  - killbots
  - kimageannotator
  - kinfocenter
  - kiriki
  - kiten
  - kiten-libs
  - kjumpingcube
  - kleopatra
  - kleopatra-libs
  - klettres
  - klickety
  - klines
  - kmag
  - kmahjongg
  - kmenuedit
  - kmines
  - kmix
  - kmousetool
  - kmouth
  - kmplot
  - knavalbattle
  - knetwalk
  - kolf
  - kollision
  - kolourpaint
  - kolourpaint-libs
  - kompare
  - kompare-libs
  - konqueror
  - konqueror-libs
  - konquest
  - konsole5
  - konsole5-part
  - konversation
  - kpartloader
  - kpmcore
  - kproperty
  - kqtquickcharts
  - krdc
  - krdc-libs
  - kreport
  - kreversi
  - krfb
  - krfb-libs
  - kruler
  - kscreen
  - kscreenlocker
  - kshisen
  - ksirk
  - ksnakeduel
  - ksnip
  - kspaceduel
  - ksquares
  - ksshaskpass
  - ksudoku
  - ksysguard
  - ksysguardd
  - ksystemlog
  - ksystemstats
  - kteatime
  - ktimer
  - ktorrent
  - ktorrent-libs
  - ktouch
  - ktuberling
  - kturtle
  - kubrick
  - kuiviewer
  - kuserfeedback
  - kuserfeedback-console
  - kwalletmanager5
  - kwayland-integration
  - kwayland-server
  - kwebkitpart
  - kwin
  - kwin-common
  - kwin-libs
  - kwin-wayland
  - kwin-x11
  - kwordquiz
  - kwrite
  - kwrited
  - layer-shell-qt
  - libaccounts-qt5
  - libkdegames
  - libkeduvocdocument
  - libkgapi
  - libkmahjongg
  - libkmahjongg-data
  - libkolabxml
  - libkomparediff2
  - libkscreen-qt5
  - libksysguard
  - libksysguard-common
  - libkworkspace5
  - lskat
  - maliit-keyboard
  - marble
  - marble-astro
  - marble-common
  - marble-qt
  - marble-widget-data
  - marble-widget-qt5
  - okteta
  - okteta-libs
  - oxygen-icon-theme
  - oxygen-sound-theme
  - PackageKit-Qt5
  - pam-kwallet
  - phonon-qt5
  - phonon-qt5-backend-gstreamer
  - php-kolabformat
  - picmi
  - plasma-applet-translator
  - plasma-applet-weather-widget
  - plasma-breeze
  - plasma-breeze-common
  - plasma-browser-integration
  - plasma-desktop
  - plasma-discover
  - plasma-discover-flatpak
  - plasma-discover-libs
  - plasma-discover-notifier
  - plasma-discover-offline-updates
  - plasma-discover-packagekit
  - plasma-discover-snap
  - plasma-disks
  - plasma-drkonqi
  - plasma-firewall
  - plasma-firewall-firewalld
  - plasma-integration
  - plasma-mediacenter
  - plasma-milou
  - plasma-nm
  - plasma-nm-fortisslvpn
  - plasma-nm-iodine
  - plasma-nm-l2tp
  - plasma-nm-mobile
  - plasma-nm-openconnect
  - plasma-nm-openswan
  - plasma-nm-openvpn
  - plasma-nm-pptp
  - plasma-nm-ssh
  - plasma-nm-sstp
  - plasma-nm-strongswan
  - plasma-nm-vpnc
  - plasma-pa
  - plasma-pass
  - plasma-pk-updates
  - plasma-systemmonitor
  - plasma-systemsettings
  - plasma-thunderbolt
  - plasma-vault
  - plasma-wayland-protocols
  - plasma-workspace
  - plasma-workspace-common
  - plasma-workspace-geolocation
  - plasma-workspace-geolocation-libs
  - plasma-workspace-libs
  - plasma-workspace-wallpapers
  - plasma-workspace-wayland
  - plasma-workspace-x11
  - polkit-kde
  - polkit-qt5-1
  - powerdevil
  - poxml
  - python3-kolabformat
  - qcachegrind
  - qca-qt5
  - qca-qt5-cyrus-sasl
  - qca-qt5-gcrypt
  - qca-qt5-gnupg
  - qca-qt5-logger
  - qca-qt5-nss
  - qca-qt5-ossl
  - qca-qt5-pkcs11
  - qca-qt5-softstore
  - qqc2-desktop-style
  - qt5ct
  - qt5-doc
  - qt5-qt3d-doc
  - qt5-qtaccountsservice
  - qt5-qtbase-doc
  - qt5-qtcharts
  - qt5-qtcharts-doc
  - qt5-qtconfiguration
  - qt5-qtconnectivity-doc
  - qt5-qtdatavis3d
  - qt5-qtdatavis3d-doc
  - qt5-qtdeclarative-doc
  - qt5-qtfeedback
  - qt5-qtgamepad
  - qt5-qtgamepad-doc
  - qt5-qtgraphicaleffects-doc
  - qt5-qtimageformats-doc
  - qt5-qtlocation-doc
  - qt5-qtmultimedia-doc
  - qt5-qtnetworkauth
  - qt5-qtpurchasing-doc
  - qt5-qtquickcontrols2-doc
  - qt5-qtquickcontrols-doc
  - qt5-qtremoteobjects
  - qt5-qtremoteobjects-doc
  - qt5-qtscript-doc
  - qt5-qtscxml
  - qt5-qtscxml-doc
  - qt5-qtsensors-doc
  - qt5-qtserialbus-doc
  - qt5-qtserialport-doc
  - qt5-qtspeech
  - qt5-qtspeech-doc
  - qt5-qtspeech-speechd
  - qt5-qtstyleplugins
  - qt5-qtsvg-doc
  - qt5-qttools-doc
  - qt5-qtvirtualkeyboard
  - qt5-qtvirtualkeyboard-doc
  - qt5-qtwayland-doc
  - qt5-qtwebchannel-doc
  - qt5-qtwebkit
  - qt5-qtwebsockets-doc
  - qt5-qtwebview-doc
  - qt5-qtx11extras-doc
  - qt5-qtxmlpatterns-doc
  - qt5-style-oxygen
  - qt-creator
  - qt-creator-data
  - qt-creator-doc
  - qt-creator-translations
  - qt-settings
  - rocs
  - rocs-libs
  - sddm
  - sddm-breeze
  - sddm-kcm
  - sddm-themes
  - signon-kwallet-extension
  - skanlite
  - spectacle
  - step
  - svgpart
  - sweeper
  - umbrello
  - xdg-desktop-portal-kde
  - yakuake

  labels:
  - eln-extras

  arch_packages:
    x86_64:
    - akonadi-calendar-tools
    - akonadiconsole
    - akonadi-import-wizard
    - akregator
    - akregator-libs
    - grantlee-editor
    - grantlee-editor-libs
    - k3b
    - k3b-libs
    - kaccounts-providers
    - kaddressbook
    - kaddressbook-libs
    - kalarm
    - kalgebra
    - kdepim-addons
    - kdepim-runtime
    - kdepim-runtime-libs
    - kdevelop
    - kdevelop-libs
    - kdevelop-pg-qt
    - kf5-akonadi-calendar
    - kf5-akonadi-contacts
    - kf5-calendarsupport
    - kf5-eventviews
    - kf5-incidenceeditor
    - kf5-kmailtransport
    - kf5-kmailtransport-akonadi
    - kf5-libgravatar
    - kf5-libkdepim
    - kf5-libksieve
    - kf5-mailcommon
    - kf5-mailimporter
    - kf5-mailimporter-akonadi
    - kf5-messagelib
    - kf5-pimcommon
    - kf5-pimcommon-akonadi
    - kgpg
    - kmail
    - kmail-account-wizard
    - kmail-libs
    - knotes
    - knotes-libs
    - kontact
    - kontact-libs
    - korganizer
    - korganizer-libs
    - kwebenginepart
    - mbox-importer
    - parley
    - pim-data-exporter
    - pim-data-exporter-libs
    - pim-sieve-editor
    - plasma-sdk
    - qt5-qtwebengine
    - qt5-qtwebengine-devtools
    - qt5-qtwebview
    aarch64:
    - akonadi-calendar-tools
    - akonadiconsole
    - akonadi-import-wizard
    - akregator
    - akregator-libs
    - grantlee-editor
    - grantlee-editor-libs
    - k3b
    - k3b-libs
    - kaccounts-providers
    - kaddressbook
    - kaddressbook-libs
    - kalarm
    - kalgebra
    - kdepim-addons
    - kdepim-runtime
    - kdepim-runtime-libs
    - kdevelop
    - kdevelop-libs
    - kdevelop-pg-qt
    - kf5-akonadi-calendar
    - kf5-akonadi-contacts
    - kf5-calendarsupport
    - kf5-eventviews
    - kf5-incidenceeditor
    - kf5-kmailtransport
    - kf5-kmailtransport-akonadi
    - kf5-libgravatar
    - kf5-libkdepim
    - kf5-libksieve
    - kf5-mailcommon
    - kf5-mailimporter
    - kf5-mailimporter-akonadi
    - kf5-messagelib
    - kf5-pimcommon
    - kf5-pimcommon-akonadi
    - kgpg
    - kmail
    - kmail-account-wizard
    - kmail-libs
    - knotes
    - knotes-libs
    - kontact
    - kontact-libs
    - korganizer
    - korganizer-libs
    - kwebenginepart
    - mbox-importer
    - parley
    - pim-data-exporter
    - pim-data-exporter-libs
    - pim-sieve-editor
    - plasma-sdk
    - qt5-qtwebengine
    - qt5-qtwebengine-devtools
    - qt5-qtwebview
