document: feedback-pipeline-workload
version: 1
data:
  name: qt6 eln-extra packages
  description: QT6 ELN Extras packages
  maintainer: tdawson
  packages:
    - python3-pyqt6-charts
    - qt6-doc
    - qt6-qtcoap
    - qt6-qtgraphs
    - qt6-qtgrpc
    - qt6-qthttpserver
    - qt6-qtmqtt
    - qt6-qtopcua
  labels:
    - eln-extras
  arch_packages:
    aarch64:
      - python3-pyqt6-webengine
      - qt6ct
      - qt6-qtquick3dphysics
      - qt6-qtwebengine
      - qt6-qtwebengine-devtools
      - qt6-qtwebview
    ppc64le:
      - qt6ct
    x86_64:
      - python3-pyqt6-webengine
      - qt6ct
      - qt6-qtquick3dphysics
      - qt6-qtwebengine
      - qt6-qtwebengine-devtools
      - qt6-qtwebview
