document: feedback-pipeline-workload
version: 1
data:
  name: Pandoc
  description: Documentation converter tool
  maintainer: petersen
  packages:
    - pandoc-cli
    # build dependencies
    - ghc-pandoc-devel
  labels:
    - eln-extras
