document: feedback-pipeline-workload
version: 1
data:
  name: initial-setup eln-extra packages
  description: Anaconda Initial Setup ELN Extras packages
  maintainer: ngompa

  packages:
  - initial-setup
  - initial-setup-gui
  - initial-setup-gui-wayland-generic


  labels:
  - eln-extras
