document: feedback-pipeline-workload
version: 1
data:
  name: Fedora Packager
  description: Tools and utilities needed by a Fedora Packager
  maintainer: epel-sig
  packages:
    - bodhi-client
    - fbrnch
    - fedora-easy-karma
    - fedora-packager
    - fedora-repoquery
    - fedpkg
    - git
    - koji
    - koji-tool
    - mock
    - pkgtreediff
    - rhbzquery
    - rpm-build
    - rpmbuild-order
    - rpmdevtools
    - rpmdistro-repoquery
  labels:
    - eln-extras
