document: feedback-pipeline-workload
version: 1
data:
  name: meta-sig packages
  description: ELN Extras packages that Meta cares about
  maintainer: meta-sig
  packages:
    - atop
    - b4
    - below
    - btrd
    - ccache
    - colm
    - ctags
    - dbench
    - debian-keyring
    - debootstrap
    - difftastic
    - dpkg
    - drgn
    - duo_unix
    - duo_unix-selinux
    - ebranch
    - et
    - fd-find
    - fping
    - git-email
    - glslang
    - htop
    - hyperfine
    - iotools
    - keyrings-filesystem
    - lei
    - libdwarf
    - libdwarf-devel
    - libidn
    - libidn-devel
    - libkdumpfile-devel
    - libxcrypt-compat
    - linux-sysinfo-snapshot
    - mkosi
    - mlnx-tools
    - mosh
    - ncurses-compat-libs
    - neovim
    - netconsd
    - ngrep
    - nss-pam-ldapd
    - packetdrill
    - packetdrill-data
    - pam_duo
    - pam_krb5
    - parallel
    - pngquant
    - poi-tracker
    - pore
    - pv
    - python3-pystemd
    - python3-testslide
    - python3-zstd
    - qrencode-devel
    - ragel
    - retsnoop
    - ripgrep
    - rpmdistro-repoquery
    - rpminspect
    - rpminspect-data-centos
    - rpminspect-data-fedora
    - rpmrebuild
    - screen
    - sdparm
    - sequoia-keyring-linter
    - stress
    - stressapptest
    - strongswan
    - tpm-tools
    - trousers
    - ubu-keyring
    - veristat
  arch_packages:
    aarch64:
      - sedutil
      - sysbench
    x86_64:
      - msr-tools
      - sedutil
      - sysbench
  labels:
    - eln-extras
