document: feedback-pipeline-workload
version: 1
data:
  name: kde eln-extra packages
  description: KDE Plasma Desktop ELN Extras packages
  maintainer: tdawson
  packages:
    - alligator
    #- amarok
    - analitza
    - ark
    #- artikulate
    - atlantik
    - audex
    - audiocd-kio
    - audiotube
    - aurorae
    - baloo-widgets
    - blinken
    - bomber
    - bovo
    - breeze-cursor-theme
    - breeze-icon-theme
    - breeze-icon-theme-rcc
    - calindori
    #- cervisia
    - colord-kde
    - dolphin
    - dolphin-plugins
    - dragon
    - elisa-player
    - extra-cmake-modules
    - ffmpegthumbs
    - filelight
    - francis
    - gcompris-qt
    - granatier
    - gwenview
    - haruna
    - isoimagewriter
    - itinerary
    - java-kolabformat
    - juk
    - kaccounts-integration-qt6
    - kactivitymanagerd
    - kajongg
    - kalk
    - kalm
    - kalzium
    - kamera
    #- kamoso
    - kanagram
    - kapman
    - kapptemplate
    - kasts
    - kate
    - kate-plugins
    - katomic
    - kbackup
    - kblackbox
    - kblocks
    - kbounce
    - kbrickbuster
    - kbruch
    - kcachegrind
    - kcachegrind-converters
    - kcalc
    - kcharselect
    - kclock
    - kcolorchooser
    - kcolorpicker-qt6
    - kcron
    #- kdb
    #- kdb-driver-mysql
    #- kdb-driver-postgresql
    - kdebugsettings
    - kde-cli-tools
    - kde-connect
    - kdeconnectd
    - kde-connect-nautilus
    - kdecoration
    - kde-dev-scripts
    - kde-dev-utils
    - kdeedu-data
    - kde-filesystem
    - kdegraphics-mobipocket
    - kdegraphics-thumbnailers
    - kde-gtk-config
    - kde-inotify-survey
    - kdenetwork-filesharing
    - kdenlive
    - kde-partitionmanager
    - kdeplasma-addons
    - kde-print-manager
    - kdesdk-kioslaves
    - kdesdk-thumbnailers
    - kde-settings
    - kde-settings-plasma
    - kde-settings-pulseaudio
    - kdesu
    - kdf
    - kdiagram
    - kdialog
    - kdiamond
    - kdnssd
    - keditbookmarks
    #- kexi
    - keysmith
    - kf6-attica
    - kf6-baloo
    - kf6-bluez-qt
    - kf6-breeze-icons
    - kf6-filesystem
    - kf6-frameworkintegration
    - kf6-kapidox
    - kf6-karchive
    - kf6-kauth
    - kf6-kbookmarks
    - kf6-kcalendarcore
    - kf6-kcmutils
    - kf6-kcodecs
    - kf6-kcolorscheme
    - kf6-kcompletion
    - kf6-kconfig
    - kf6-kconfigwidgets
    - kf6-kcontacts
    - kf6-kcoreaddons
    - kf6-kcrash
    - kf6-kdav
    - kf6-kdbusaddons
    - kf6-kdeclarative
    - kf6-kded
    - kf6-kdesu
    - kf6-kdnssd
    - kf6-kdoctools
    - kf6-kfilemetadata
    - kf6-kglobalaccel
    - kf6-kguiaddons
    - kf6-kholidays
    - kf6-ki18n
    - kf6-kiconthemes
    - kf6-kidletime
    - kf6-kimageformats
    - kf6-kio
    - kf6-kirigami
    - kf6-kirigami-addons
    - kf6-kitemmodels
    - kf6-kitemviews
    - kf6-kjobwidgets
    - kf6-knewstuff
    - kf6-knotifications
    - kf6-knotifyconfig
    - kf6-kpackage
    - kf6-kparts
    - kf6-kpeople
    - kf6-kplotting
    - kf6-kpty
    - kf6-kquickcharts
    - kf6-krunner
    - kf6-kservice
    - kf6-kstatusnotifieritem
    - kf6-ksvg
    - kf6-ktexteditor
    - kf6-ktexttemplate
    - kf6-ktextwidgets
    - kf6-kunitconversion
    - kf6-kuserfeedback
    - kf6-kwallet
    - kf6-kwidgetsaddons
    - kf6-kwindowsystem
    - kf6-kxmlgui
    - kf6-modemmanager-qt
    - kf6-networkmanager-qt
    - kf6-prison
    - kf6-purpose
    - kf6-qqc2-desktop-style
    - kf6-rpm-macros
    - kf6-solid
    - kf6-sonnet
    - kf6-syndication
    - kf6-syntax-highlighting
    - kf6-threadweaver
    - kfind
    - kfourinline
    - kgeography
    - kget
    - kgoldrunner
    - kgraphviewer
    - khangman
    #- kig
    - kigo
    - kile
    - killbots
    - kimageannotator-qt6
    - kinfocenter
    - kio-admin
    - kirigami-gallery
    - kiriki
    - kiten
    - kjournald
    - kjumpingcube
    - kleopatra
    - klettres
    - klickety
    - klines
    - kmag
    - kmahjongg
    - kmenuedit
    - kmines
    - kmix
    - kmousetool
    - kmouth
    - kmplot
    - knavalbattle
    - knetwalk
    - knights
    - koko
    - kolf
    - kollision
    - kolourpaint
    - kommit
    - kompare
    - kongress
    - konquest
    - konsole
    - konsole-part
    - kontrast
    - konversation
    - kpartloader
    - kpmcore
    #- kproperty
    #- kqtquickcharts
    - krdc
    - krdp
    - krecorder
    #- kreport
    - kreversi
    - krfb
    - kruler
    - kscreen
    - kscreenlocker
    - kshisen
    - ksirk
    - ksnakeduel
    - ksnip
    - kspaceduel
    - ksquares
    - ksshaskpass
    - ksudoku
    - ksystemlog
    - ksystemstats
    - kteatime
    - ktimer
    - ktorrent
    #- ktouch
    - ktrip
    - ktuberling
    - kturtle
    - kubrick
    - kuiviewer
    - kuserfeedback
    - kuserfeedback-console
    - kwalletmanager5
    - kwave
    - kweather
    - kwin
    - kwordquiz
    - kwrite
    - kwrited
    - layer-shell-qt
    - libkdegames
    - libkeduvocdocument
    - libkgapi
    - libkmahjongg
    - libkmahjongg-data
    - libkolabxml
    - libkomparediff2
    - libksysguard
    - libkworkspace6
    - lokalize
    - lskat
    - maliit-keyboard
    - marble
    - marble-astro
    - marble-plasma
    - marble-qt
    - marble-widget-data
    - markdownpart
    - marknote
    - massif-visualizer
    - minuet
    - neochat
    - nheko
    - okular
    - okular-mobile
    #- okteta
    - oxygen-icon-theme
    - oxygen-sound-theme
    - palapeli
    - pam-kwallet
    - phonon-qt6
    - phonon-qt6-backend-vlc
    - php-kolabformat
    - picmi
    - plasma-breeze
    - plasma-browser-integration
    - plasma-desktop
    - plasma-discover
    - plasma-discover-flatpak
    - plasma-discover-notifier
    - plasma-discover-offline-updates
    - plasma-discover-packagekit
    - plasma-discover-snap
    - plasma-disks
    - plasma-drkonqi
    - plasma-firewall
    - plasma-firewall-firewalld
    - plasma-integration
    - plasma-milou
    - plasma-mobile
    - plasma-mobile-sounds
    - plasma-nm
    - plasma-nm-fortisslvpn
    - plasma-nm-openswan
    - plasma-nm-openvpn
    - plasma-nm-pptp
    - plasma-nm-sstp
    - plasma-nm-strongswan
    - plasma-pa
    - plasma-pass
    - plasma-settings
    - plasma-systemmonitor
    - plasma-systemsettings
    - plasma-thunderbolt
    - plasmatube
    - plasma-vault
    - plasma-wayland-protocols
    - plasma-welcome
    - plasma-workspace
    - plasma-workspace-geolocation
    - plasma-workspace-wallpapers
    - polkit-kde
    - polkit-qt6-1
    - powerdevil
    - poxml
    - python3-kolabformat
    - qcachegrind
    - qmlkonsole
    - qqc2-breeze-style
    - qrca
    - qt-creator
    - qt-creator-data
    - qt-creator-doc
    - qt-creator-translations
    - qt-settings
    #- rocs
    - ruqola
    - sddm
    - sddm-breeze
    - sddm-kcm
    - sddm-themes
    - signon-kwallet-extension
    - skanlite
    - skladnik
    - spacebar
    - spectacle
    - step
    - svgpart
    - sweeper
    #- umbrello
    - xdg-desktop-portal-kde
    - xwaylandvideobridge
    - yakuake
  labels:
    - eln-extras
  arch_packages:
    x86_64:
      - akonadi-calendar-tools
      - akonadiconsole
      - akonadi-import-wizard
      - akregator
      - angelfish
      - arianna
      - bluedevil
      - cantor
      - digikam
      - falkon
      - ghostwriter
      - grantlee-editor
      - k3b
      - kaccounts-providers
      - kaddressbook
      - kaidan
      - kalarm
      - kalgebra
      - kdepim-addons
      - kdepim-runtime
      - kdevelop
      - kdevelop-pg-qt
      - kgpg
      - khelpcenter
      - kio-gdrive
      - kmail
      - kmail-account-wizard
      - konqueror
      - kontact
      - korganizer
      - kwebenginepart
      - mbox-importer
      - merkuro
      - parley
      - pim-data-exporter
      - pim-sieve-editor
      - plasma-nm-l2tp
      - plasma-nm-openconnect
      - plasma-sdk
      - skanpage
      - tokodon
    aarch64:
      - akonadi-calendar-tools
      - akonadiconsole
      - akonadi-import-wizard
      - akregator
      - angelfish
      - arianna
      - bluedevil
      - cantor
      - digikam
      - falkon
      - ghostwriter
      - grantlee-editor
      - k3b
      - kaccounts-providers
      - kaddressbook
      - kaidan
      - kalarm
      - kalgebra
      - kdepim-addons
      - kdepim-runtime
      - kdevelop
      - kdevelop-pg-qt
      - kgpg
      - khelpcenter
      - kio-gdrive
      - kmail
      - kmail-account-wizard
      - konqueror
      - kontact
      - korganizer
      - kwebenginepart
      - mbox-importer
      - merkuro
      - parley
      - pim-data-exporter
      - pim-sieve-editor
      - plasma-nm-l2tp
      - plasma-nm-openconnect
      - plasma-sdk
      - skanpage
      - tokodon
    ppc64le:
      - akonadi-calendar-tools
      - akonadiconsole
      - akonadi-import-wizard
      - akregator
      - angelfish
      - arianna
      - bluedevil
      - cantor
      - digikam
      - falkon
      - ghostwriter
      - grantlee-editor
      - k3b
      - kaccounts-providers
      - kaddressbook
      - kaidan
      - kalarm
      - kalgebra
      - kdepim-addons
      - kdepim-runtime
      - kdevelop
      - kdevelop-pg-qt
      - kgpg
      - khelpcenter
      - kio-gdrive
      - kmail
      - kmail-account-wizard
      - konqueror
      - kontact
      - korganizer
      - kwebenginepart
      - mbox-importer
      - merkuro
      - parley
      - pim-data-exporter
      - pim-sieve-editor
      - plasma-nm-l2tp
      - plasma-nm-openconnect
      - plasma-sdk
      - skanpage
      - tokodon
