document: feedback-pipeline-workload
version: 1
data:
  name: meta-sig data science packages
  description: ELN Extras packages for data science
  maintainer: meta-sig
  packages:
    - conda
    # has several header-only dependencies
    - libmamba-devel
  labels:
    - eln-extras
