document: feedback-pipeline-workload
version: 1
data:
  name: cinnamon eln-extra packages
  description: Cinnamon Desktop ELN Extras packages
  maintainer: yselkowitz
  packages:
    - cinnamon
    - cinnamon-calendar-server
    - cinnamon-control-center
    - cinnamon-desktop
    - cinnamon-menus
    - cinnamon-screensaver
    - cinnamon-session
    - cinnamon-settings-daemon
    - cinnamon-translations
    - cjs
    - folder-color-switcher-nemo
    - gnome-icon-theme
    - gnome-online-accounts-gtk
    - mintlocale
    - mint-themes
    - mint-x-icons
    - mint-y-icons
    - mint-y-theme
    - muffin
    - nemo
    - nemo-audio-tab
    - nemo-compare
    - nemo-emblems
    - nemo-fileroller
    - nemo-image-converter
    - nemo-pastebin
    - nemo-preview
    - nemo-seahorse
    - nemo-search-helpers
    - nemo-terminal
    - paper-icon-theme
    - python3-xapp
    - xapps
    - xdg-desktop-portal-xapp
    - xed
    - xreader
    - xreader-thumbnailer
    # external apps
    - blueman
    - gnome-screenshot
    - gnome-terminal
    - touchegg
  labels:
    - eln-extras
