document: feedback-pipeline-workload
version: 1
data:
  name: LibreOffice
  description: LibreOffice office suite
  maintainer: libreoffice-sig
  packages:
    # apps
    - libreoffice
    - libreoffice-base
    - libreoffice-calc
    - libreoffice-draw
    - libreoffice-impress
    - libreoffice-math
    - libreoffice-writer
    # extensions
    - libreoffice-emailmerge
    - libreoffice-filters
    - libreoffice-librelogo
    - libreoffice-nlpsolver
    - libreoffice-ogltrans
    - libreoffice-postgresql
    - libreoffice-wiki-publisher
    # integration plugins
    - libreoffice-gtk3
    - libreoffice-kf6
    - libreoffice-x11
    # langpacks (those with missing deps are commented out)
    - libreoffice-langpack-af
    - libreoffice-langpack-ar
    - libreoffice-langpack-as
    - libreoffice-langpack-be
    - libreoffice-langpack-bg
    - libreoffice-langpack-bn
    - libreoffice-langpack-br
    - libreoffice-langpack-ca
    - libreoffice-langpack-cs
    - libreoffice-langpack-cy
    - libreoffice-langpack-da
    - libreoffice-langpack-de
    - libreoffice-langpack-dz
    - libreoffice-langpack-el
    - libreoffice-langpack-en
    - libreoffice-langpack-eo
    - libreoffice-langpack-es
    - libreoffice-langpack-et
    - libreoffice-langpack-eu
    - libreoffice-langpack-fa
    - libreoffice-langpack-fi
    - libreoffice-langpack-fr
    - libreoffice-langpack-fy
    - libreoffice-langpack-ga
    - libreoffice-langpack-gl
    - libreoffice-langpack-gu
    - libreoffice-langpack-he
    - libreoffice-langpack-hi
    - libreoffice-langpack-hr
    - libreoffice-langpack-hu
    - libreoffice-langpack-id
    - libreoffice-langpack-it
    - libreoffice-langpack-ja
    - libreoffice-langpack-ka
    - libreoffice-langpack-kk
    - libreoffice-langpack-kn
    - libreoffice-langpack-ko
    - libreoffice-langpack-lt
#    - libreoffice-langpack-lv
    - libreoffice-langpack-mai
    - libreoffice-langpack-ml
    - libreoffice-langpack-mr
#    - libreoffice-langpack-nb
    - libreoffice-langpack-nl
#    - libreoffice-langpack-nn
    - libreoffice-langpack-nr
    - libreoffice-langpack-nso
    - libreoffice-langpack-or
    - libreoffice-langpack-pa
    - libreoffice-langpack-pl
    - libreoffice-langpack-pt-BR
    - libreoffice-langpack-pt-PT
    - libreoffice-langpack-ro
    - libreoffice-langpack-ru
    - libreoffice-langpack-si
    - libreoffice-langpack-sk
    - libreoffice-langpack-sl
    - libreoffice-langpack-sr
    - libreoffice-langpack-ss
    - libreoffice-langpack-st
    - libreoffice-langpack-sv
    - libreoffice-langpack-ta
    - libreoffice-langpack-te
    - libreoffice-langpack-th
    - libreoffice-langpack-tn
    - libreoffice-langpack-tr
    - libreoffice-langpack-ts
    - libreoffice-langpack-uk
    - libreoffice-langpack-ve
    - libreoffice-langpack-xh
    - libreoffice-langpack-zh-Hans
    - libreoffice-langpack-zh-Hant
    - libreoffice-langpack-zu
    # third-party extensions
    - libreoffice-gallery-vrt-network-equipment
    - openoffice.org-diafilter
  labels:
    - eln-extras
