document: feedback-pipeline-workload
version: 1
data:
  name: meta-sig packages
  description: ELN Extras packages that Meta cares about
  maintainer: meta-sig

  packages:
  - atop
  - awscli
  - awscli2
  - azure-cli
  - b4
  - below
  - btrd
  - ccache
  - colm
  - ctags
  - dbench
  - debian-keyring
  - debootstrap
  - difftastic
  - dnf5
  - dnf5-plugins
  - dnf5daemon-client
  - dnf5daemon-server
  - dpkg
  - drgn
  - duo_unix
  - duo_unix-selinux
  - ebranch
  - et
  - exa
  - htop
  - iotools
  - fd-find
  - fping
  - glslang
  - hyperfine
  - keyrings-filesystem
  - lei
  - libdnf5
  - libdnf5-cli
  - libdnf5-plugin-actions
  - libdwarf
  - libdwarf-devel
  - libkdumpfile-devel
  - libidn
  - libidn-devel
  - mlnx-tools
  - mkosi
  - mosh
  - ncdu
  - ncurses-compat-libs
  - neovim
  - netconsd
  - ngrep
  - packetdrill
  - packetdrill-data
  - pam_duo
  - pam_krb5
  - parallel
  - pngquant
  - pore
  - pv
  - python3-dnf-plugin-flunk_dependent_remove
  - python3-libdnf5
  - python3-libdnf5-cli
  - python3-libdnf5-python-plugins-loader
  - python3-pystemd
  - python3-testslide
  - python3-zstd
  - rpmdistro-repoquery
  - rpminspect
  - rpminspect-data-centos
  - rpminspect-data-fedora
  - rpmrebuild
  - ruby-libdnf5
  - ruby-libdnf5-cli
  - qrencode-devel
  - ragel
  - retsnoop
  - ripgrep
  - screen
  - sdparm
  - sequoia-keyring-linter
  - stress
  - stressapptest
  - strongswan
  - tpm-tools
  - trousers
  - ubu-keyring
  - veristat

  arch_packages:
    aarch64:
      - sedutil
      - sysbench
    i686:
      - msr-tools
      - sedutil
      - sysbench
    ppc64le:
      - sedutil
    x86_64:
      - msr-tools
      - sedutil
      - sysbench

  labels:
  - eln-extras
