---
# This configuration file defines a "Repository" in Feedback Pipeline.
# https://tiny.distro.builders
#
# Repositories are the sources of the data.
# Right now, they represent Fedora releases, but can be extended in the future.

document: feedback-pipeline-repository
version: 2
data:
  # id is the filename â€” that automatically prevents collisions for free!


  ### MANDATORY FIELDS ###
  
  # Name is an identifier for humans
  #
  # (mandatory field)
  name: Fedora rawhide
  
  # A short description, perhaps hinting the purpose
  #
  # (mandatory field)
  description: Official Fedora rawhide release

  # Who maintains it? This is just a freeform string
  # for humans to read. In Fedora, a FAS nick is recommended.
  #
  # (mandatory field)
  maintainer: asamalik

  # Where does this repository come from?
  # Right now, only Fedora repositories are supported,
  # defined by their releasever.
  # 
  # (mandatory field)
  source:
 
    repos:

      everything:
        baseurl: https://kojipkgs.fedoraproject.org/compose/rawhide/latest-Fedora-Rawhide/compose/Everything/$basearch/os/
      
    releasever: "rawhide"

    architectures:
    - aarch64
    - i686
    - ppc64le
    - s390x
    - x86_64
