---
document: feedback-pipeline-repository
version: 2
data:
  name: Fedora ELN (backed by rawhide)
  description: Fedora ELN with rawhide as a backup for missing packages
  maintainer: asamalik
  source:
    repos:
      BaseOS:
        baseurl: https://kojipkgs.fedoraproject.org/compose/eln/latest-Fedora-eln/compose/BaseOS/$basearch/os/
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
        exclude: &eln_excludes
        # java-latest is EPEL only
        - java-latest-openjdk*
        # ffmpeg is unwanted
        - libav*-free
        - libpostproc-free
        - libswresample-free
        - libswscale-free
        # qtwebengine is unwanted
        - qt6-qtpdf
        - qt6-qtwebengine
        # unwanted weak dependency of ibus-table, ibus-typing-booster
        - python3-simpleaudio
        priority: 1
      AppStream:
        baseurl: https://kojipkgs.fedoraproject.org/compose/eln/latest-Fedora-eln/compose/AppStream/$basearch/os/
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
        exclude: *eln_excludes
        priority: 1
      CRB:
        baseurl: https://kojipkgs.fedoraproject.org/compose/eln/latest-Fedora-eln/compose/CRB/$basearch/os/
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
        exclude: *eln_excludes
        priority: 1
      HA:
        baseurl: https://kojipkgs.fedoraproject.org/compose/eln/latest-Fedora-eln/compose/HighAvailability/$basearch/os/
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
        limit_arches: ["aarch64", "ppc64le", "s390x", "x86_64"]
        priority: 2
      NFV:
        baseurl: https://kojipkgs.fedoraproject.org/compose/eln/latest-Fedora-eln/compose/NFV/$basearch/os/
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
        limit_arches: ["x86_64"]
        priority: 2
      RT:
        baseurl: https://kojipkgs.fedoraproject.org/compose/eln/latest-Fedora-eln/compose/RT/$basearch/os/
        priority: 2
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
        limit_arches: ["x86_64"]
      SAP:
        baseurl: https://kojipkgs.fedoraproject.org/compose/eln/latest-Fedora-eln/compose/SAP/$basearch/os/
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
        limit_arches: ["ppc64le", "s390x", "x86_64"]
        priority: 2
      SAPHANA:
        baseurl: https://kojipkgs.fedoraproject.org/compose/eln/latest-Fedora-eln/compose/SAPHANA/$basearch/os/
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
        limit_arches: ["ppc64le", "x86_64"]
        priority: 2
      buildroot:
        baseurl: https://kojipkgs.fedoraproject.org/repos/eln-build/latest/$basearch/
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
        exclude: &eln_build_excludes
        # prefer bind
        - bind9-next*
        # prefer postfix and sendmail
        - esmtp
        - esmtp-local-delivery
        - exim
        - opensmtpd
        # RHEL packages are named ipa*
        - freeipa*
        # openjdk-portable packages are built against the oldest supported
        # RHEL version, will not be imported into next RHEL version
        - java-*-openjdk-portable*
        # java-latest is EPEL only
        - java-latest-openjdk*
        # prefer pipewire-jack
        - jack-audio-connection-kit
        # doc generation tools with unwanted dependencies
        - fop
        - ImageMagick
        # pulls in GHC stack
        - pandoc
        # unwanted ocaml deps
        - ocaml-ounit*
        # unwanted python deps
        - python3-anyio
        - python3-coverage
        - python3-docs
        - python3-etcd
        - python3-flask
        - python3-furo
        - python3-freezegun
        - python3-hypercorn
        - python3-hypothesis
        - python3-iso8601
        - python3-ipython
        - python3-myst-parser
        - python3-pillow
        - python3-pretend
        - python3-pyOpenSSL
        - python3-pysocks
        - python3-pytest-benchmark
        - python3-pytest-cov
        - python3-pytest-flakes
        - python3-pytest-mock
        - python3-pytest-randomly
        - python3-pytest-timeout
        - python3-pytest-xdist
        - python3-pywbem
        - python3-quart
        - python3-quart-trio
        - python3-recommonmark
        - python3-scikit-build-core
        - python3-subunit
        - python3-tomlkit
        - python3-tox-current-env
        - python3-trio
        - python3-trustme
        - python3-twisted
        - python3-werkzeug
        - tox
        # prefer grubby
        - sdubby
        # ffmpeg is unwanted
        - ffmpeg-free-devel
        - libav*-free*
        - libpostproc-free*
        - libswresample-free*
        - libswscale-free*
        # only qt6 in ELN
        - qt5-*
        # qtwebengine is unwanted
        - qt6-qtpdf
        - qt6-qtpdf-devel
        - qt6-qtwebengine
        - qt6-qtwebengine-devel
        # xen is unwanted
        - xen-libs
        - xen-devel
        # rust lib crates are unwanted; dependencies must be vendored
        - cargo-c
        - cargo-rpm-macros
        - rust-srpm-macros
        - rust-*-devel
        # ELN has only a subset of texlive; avoid components only in Fedora
        - texlive-xindy
        # unwanted toolchain
        - mold
        # dogtag-pki build deps which are vendored in RHEL
        - fasterxml-oss-parent
        - jackson-*
        - jboss-jaxrs-2.0-api
        - jboss-logging*
        - pki-resteasy-*
        # unwanted weak dependency of ibus-table, ibus-typing-booster
        - python3-simpleaudio
        # unwanted (and rarely used) build dep, pulls in hundreds of Perl deps
        - licensecheck
        priority: 4
      Rawhide:
        baseurl: https://kojipkgs.fedoraproject.org/compose/rawhide/latest-Fedora-Rawhide/compose/Everything/$basearch/os/
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
        exclude: *eln_build_excludes
        priority: 5
    releasever: "rawhide"
    architectures:
      - aarch64
      - ppc64le
      - s390x
      - x86_64
    composeinfo: https://kojipkgs.fedoraproject.org/compose/eln/latest-Fedora-eln/compose/metadata/composeinfo.json
    base_buildroot_override: ['bash', 'bzip2', 'coreutils', 'cpio', 'diffutils', 'findutils', 'gawk', 'glibc-minimal-langpack', 'grep', 'gzip', 'info', 'make', 'patch', 'redhat-rpm-config', 'rpm-build', 'sed', 'shadow-utils', 'tar', 'unzip', 'util-linux', 'which', 'xz']
