document: feedback-pipeline-workload
version: 1
data:
  name: Platform Storage
  description: Platform Storage Supported Packages
  maintainer: rhel-sst-logical-storage
  packages:
    # Stratis
    - python3-dbus-client-gen
    - python3-dbus-python-client-gen
    - python3-dbus-signature-pyparsing
    - python3-into-dbus-python
    - python3-justbases
    - python3-justbytes
    - python3-wcwidth
    - stratis-cli
    - stratisd
    # LVM
    # Boom-boot and its sub-packages
    - boom-boot
    - boom-boot-conf
    - python3-boom
    # Snapshot manager and its sub-packages
    - snapm
    - python3-snapm
    - python3-snapm-doc
    # cryptsetup and its sub-packages
    - cryptsetup
    - cryptsetup-devel
    - cryptsetup-libs
    - integritysetup
    - veritysetup
    # lvm2 and its sub-packages
    - device-mapper
    - device-mapper-devel
    - device-mapper-event
    - device-mapper-event-devel
    - device-mapper-event-libs
    - device-mapper-libs
    - device-mapper-multipath
    - device-mapper-persistent-data
    - lvm2
    - lvm2-dbusd
    - lvm2-devel
    - lvm2-libs
    - lvm2-lockd
    - mdadm
    - sanlock
    - stratisd
    - userspace-rcu
    - vdo
  labels:
    - eln
    - c10s
