document: feedback-pipeline-workload
version: 1
data:
  name: Debuggers
  description: Debuggers and components
  maintainer: rhel-sst-pt-perf-debug
  packages:
    - gdb
    - gdb-doc
    - gdb-gdbserver
    - gdb-headless
    - gdb-minimal
    - libbabeltrace
    - libbabeltrace-devel
    - source-highlight
    # See libipt below
  labels:
    - eln
    - c10s
  # libipt is Intel only
  arch_packages:
    x86_64:
      - libipt
