document: feedback-pipeline-workload
version: 1
data:
  name: Boost
  description: Boost provides free peer-reviewed portable C++ source libraries
  maintainer: rhel-sst-pt-libraries
  packages:
    - boost
    - boost-b2
    - boost-build
    - boost-devel
    - boost-doc
    - boost-doctools
    - boost-examples
    - boost-graph-mpich
    - boost-graph-openmpi
    - boost-mpich
    - boost-mpich-devel
    - boost-mpich-python3
    - boost-numpy3
    - boost-openmpi
    - boost-openmpi-devel
    - boost-openmpi-python3
    - boost-python3
    - boost-static
  labels:
    - eln
    - c10s
