document: feedback-pipeline-workload
version: 1
data:
  name: CSI Client Tools
  description: Red Hat tools for Content, Subscriptions and Insights.
  maintainer: rhel-sst-csi-client-tools
  packages:
    - python3-subscription-manager-rhsm
    - subscription-manager
    - subscription-manager-cockpit
    - subscription-manager-plugin-ostree
    - subscription-manager-rhsm-certificates
    - virt-who
    - yggdrasil
    - yggdrasil-worker-package-manager
  package_placeholders:
    - srpm_name: insights-client
      rpms:
        - rpm_name: insights-client
          description: insights-client
          dependencies:
            - coreutils
            - gpg
            - pciutils
            - policycoreutils-python-utils
            - python3-pyyaml
            - python3-requests
            - systemd
            - tar
    - srpm_name: rhc
      rpms:
        - rpm_name: rhc
          description: rhc
          dependencies:
            - policycoreutils-python-utils
            - yggdrasil
            - yggdrasil-worker-package-manager
    - srpm_name: rhc-worker-playbook
      rpms:
        - rpm_name: rhc-worker-playbook
          description: rhc-worker-playbook
          dependencies:
            - ansible-core
            - python3-pyyaml
            - python3-requests
    - srpm_name: rhc-playbook-verifier
      rpms:
        - rpm_name: rhc-playbook-verifier
          description: rhc-playbook-verifier
          dependencies:
            - python3-pyyaml
    - srpm_name: redhat-cloud-client-configuration
      rpms:
        - rpm_name: redhat-cloud-client-configuration
          description: redhat-cloud-client-configuration
          dependencies:
            - subscription-manager
            - systemd
    - srpm_name: insights-core
      rpms:
        - rpm_name: insights-core
          description: insights-core
          dependencies:
            - python3
            - python3-pyyaml
            - python3-requests
            - python3-rpm
        - rpm_name: insights-core-selinux
          description: insights-core-selinux
          dependencies:
            - selinux-policy
            - selinux-policy-targeted
  labels:
    - eln
    - c10s
