document: feedback-pipeline-workload
version: 1
data:
  name: Mozilla Firefox
  description: Default web browser for Workstation
  maintainer: rhel-sst-display-productivity
  packages:
    - firefox
  labels:
    # This package is only in ELN Extras because in RHEL we're using a different
    # packaging than in Fedora (and in fact in RHEL 10 this will be shipped in
    # Flatpak only), and this package pulls things into regular ELN which won't
    # be needed in RHEL. On the other hand, we're still interested in knowing
    # how this package works with all the extra ELN bits such as extra hardening
    # flags and others and apparently that's what eln-extras is for.
    - eln-extras
