document: feedback-pipeline-workload
version: 1
data:
  name: thermald
  description: Thermal Management daemon
  maintainer: rhel-sst-display-hardware-multimedia 
  packages: []
  labels:
    - eln
    - c10s
  arch_packages:
    x86_64:
      - thermald
