document: feedback-pipeline-workload
version: 1
data:
  name: Power Management
  description: Power Management related software
  maintainer: rhel-sst-cs-net-perf-services
  packages:
    - powertop
  arch_packages:
    aarch64:
      # acpid (ExclusiveArch: ia64 x86_64 %{ix86} %{arm} aarch64)
      - acpid
    x86_64:
      # acpid (ExclusiveArch: ia64 x86_64 %{ix86} %{arm} aarch64)
      - acpid
  labels:
    - eln
    - c10s
