document: feedback-pipeline-workload
version: 1
data:
  name: Python devel (CRB)
  description: Python development packages, distributed in the CRB
  maintainer: rhel-pt-python
  packages:
    - python3-devel
    - python3-debug
    - python3-test
    - python3-idle
    - python3-rpm-generators
    - python3-rpm-macros
    - python-srpm-macros
    - python-rpm-macros
    - pyproject-rpm-macros
    - python3-setuptools
    - python3-flit-core
    - python3-cython
    - python3-sphinx
    - python3-pytest
    - py3c-devel
    - py3c-doc
    - marshalparser
    - python3-hatchling
    # the following packages are anticipated to be used by pyproject-rpm-macros
    # in the feature, so we want them in CRB early,
    # rather than going trough a tad tedious process to add them after GA
    - python3-build
    - python3-installer
    - python3-pyproject-hooks
    # update the following to the main Python version when it changes
    # (for c11s we want this to be 3.15)
    - python3.14-freethreading
    - python3.14-freethreading-debug
    - python3.14-freethreading-devel
    - python3.14-freethreading-idle
    - python3.14-freethreading-libs
    - python3.14-freethreading-test
    - python3.14-freethreading-tkinter
  labels:
    - eln
