document: feedback-pipeline-workload
version: 1
data:
  name: Ruby 4.0 runtime
  description: Ruby 4.0 interpreter and DB connectors
  maintainer: rhel-pt-ruby-nodejs
  packages:
    - ruby4.0
    - ruby4.0-doc
    - ruby4.0-devel
    - ruby4.0-rubygem-mysql2
    - ruby4.0-rubygem-pg
  labels:
    - c10s
