document: feedback-pipeline-workload
version: 1
data:
  name: realtime-setup
  description: Package that creates realtime group and limits
  maintainer: rhel-sst-kernel-rts
  packages: []
  arch_packages:
    x86_64:
      - realtime-setup
  labels:
    - eln
    - c10s
