document: feedback-pipeline-workload
version: 1
data:
  name: rasdaemon
  description: Utility to receive RAS error tracings
  maintainer: rhel-sst-kernel-ft
  packages: []
  labels: # <-- Please leave
    - eln #     this unchanged.
    - c10s
  # (Only include the following section if you have arch-specific packages.)
  #   arch_packages:
  #       x86_64:                    # <-- Architecture
  #           - arch-specific-package1   # <-- The list of binary RPM packages
  #               - arch-specific-package1   #     goes here.
  #
  arch_packages:
    x86_64:
      - rasdaemon
      # asamalik debuginfo packages are special and not in the repos. 
      #- rasdaemon-debuginfo
      #- rasdaemon-debugsource
    aarch64:
      - rasdaemon
      # asamalik debuginfo packages are special and not in the repos. 
      #- rasdaemon-debuginfo
      #- rasdaemon-debugsource
    ppc64le:
      - rasdaemon
      # asamalik debuginfo packages are special and not in the repos. 
      #- rasdaemon-debuginfo
      #- rasdaemon-debugsource
