document: feedback-pipeline-workload
version: 1
data:
  name: Package Manager
  description: Recommended installation of package manager and plugins
  maintainer: rhel-sst-cs-software-management
  packages:
    - dnf5
    - dnf5-plugin-automatic
    - dnf5-plugins
    - dnf5daemon-client
    - dnf5daemon-server
    - libdnf5-plugin-actions
    - librhsm
    - python3-libdnf5
    - python3-libdnf5-cli
    - python3-libdnf5-python-plugins-loader
    - rpm
    - rpm-apidocs
    - rpm-cron
    - rpm-plugin-ima
    - rpm-plugin-selinux
    - rpm-plugin-syslog
    - rpm-plugin-systemd-inhibit
    - ruby-libdnf5
    - ruby-libdnf5-cli
    - scl-utils
  labels:
    - eln
