document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted packages from PT Python Ruby Node.js SST
  description: Packages we do not want to ship for PT Python Ruby Node.js SST
  maintainer: rhel-sst-pt-python-ruby-nodejs
  unwanted_packages:
    - js-uglify
    - web-assets-devel
  labels:
    - eln
    - c10s
