document: feedback-pipeline-workload
version: 1
data:
  name: LLVM Toolset
  description: Collection of packages providing and LLVM-based compiler toolchain.
  maintainer: rhel-sst-pt-llvm-rust-go
  packages:
    - llvm
    - llvm-devel
    - llvm-googletest
    - llvm-libs
    - llvm-static
    - llvm-test
    - llvm-toolset
    - clang
    - clang-devel
    - clang-libs
    - clang-tools-extra
    - clang-resource-filesystem
    - git-clang-format
    - python3-clang
    - compiler-rt
    - libomp
    - libomp-devel
    - lld
    - lld-devel
    - lld-libs
    - lldb
    - lldb-devel
    - python3-lldb
    - python3-lit
  labels:
    - eln
    - c10s
