document: feedback-pipeline-unwanted
version: 1
data:
  name: Core Services Network and Performance Services - Blocked packages
  description: Core Services Network and Performance Services - Packages which should not be in ELN
  maintainer: rhel-sst-cs-net-perf-services
  unwanted_packages:
    # a2ps
    - a2ps
    # authd
    - authd
    # bind
    - bind-export-libs
    - bind-sdb
    - bind-sdb-chroot
    # compat-guile18
    - compat-guile18-devel
    - compat-guile18
    # dnssec-trigger
    - dnssec-trigger
    - dnssec-trigger-panel
    # espeak
    - espeak-devel
    - espeak
    # frr
    - frr-contrib
    - frr-devel
    # GeoIP
    - GeoIP
    - GeoIP-data
    - GeoIP-devel
    # geoipupdate
    - geoipupdate
    # gsm
    - gsm-tools
    # ghostscript
    - ghostscript-x11
    # gutenprint
    - gutenprint-extras
    - gutenprint-plugin
    - gutenprint-libs-ui
    # hplip
    - hplip-gui
    # libidn
    - libidn
    - libidn-devel
    # libmemcached
    - libmemcached-awesome
    - libmemcached-awesome-devel
    - libmemcached-awesome-tools
    # libotr
    - libotr
    - libotr-devel
    # libwvstreams
    - libwvstreams-devel
    - libwvstreams
    - libwvstreams-static
    # mailman
    - mailman
    # memcached
    - memcached-devel
    # mod_security
    - mod_security
    - mod_security-mlogc
    - mod_security_crs
    # ncurses
    - ncurses-compat-libs
    - ncurses-static
    # ppp
    - network-scripts-ppp
    # ntp
    - ntp
    - ntpdate
    - sntp
    - ntp-doc
    - ntp-perl
    # perl-PerlIO-gzip
    - perl-PerlIO-gzip
    # pptp
    - pptp-setup
    # python-pyudev
    - python3-pyudev-qt5
    # quagga
    - quagga
    - quagga-contrib
    - quagga-devel
    # rsh
    - rsh
    - rsh-server
    # sane-frontends
    - sane-frontends
    # sendmail
    - sendmail
    - sendmail-cf
    - sendmail-doc
    - sendmail-milter
    - sendmail-milter-devel
    # slang
    - slang-slsh
    # spamassassin
    - spamassassin
    # speex
    - speex-tools
    # system-config-printer
    - system-config-printer
    - system-config-printer-applet
    # timedatex
    - timedatex
    # tuned
    - tuned-profiles-compat
    - tuned-profiles-nfv-host-bin
    - tuned-utils-systemtap
    # urw-base35-fonts
    - urw-base35-fonts-legacy
    # xsane
    - xsane
    - xsane-gimp
    # subversion
    - subversion-kde
    # exim
    - exim
    # pakchois
    - pakchois
    # replaced by xdebug3
    - php-pecl-xdebug
  labels:
    - eln
    - c10s
