document: feedback-pipeline-workload
version: 1
data:
  name: Python development packages
  description: Packages needed to build Python RPM packages
  maintainer: rhel-pt-python
  packages:
    - python3-devel
    - python3-rpm-generators
    - python3-rpm-macros
    - python-srpm-macros
    - python-rpm-macros
    - pyproject-srpm-macros
  labels:
    - eln
    - c10s
