document: feedback-pipeline-workload
version: 1
data:
  name: Mail Transfer Agent (MTA) and utilities
  description: Software for transfering electronic mail between computers
  maintainer: rhel-sst-cs-net-perf-services
  packages:
    - postfix
    - postfix-cdb
    - postfix-ldap
    - postfix-mysql
    - postfix-pcre
    - postfix-perl-scripts
    - postfix-pgsql
    - postfix-sqlite
    - procmail
  labels:
    - eln
    - c10s
