document: feedback-pipeline-workload
version: 1
data:
  name: Packages for crypto-development
  description: Packages needed to build against crypto libraries
  maintainer: rhel-sst-security-crypto
  packages:
    - openssl-devel
    - gnutls-devel
    - nss-devel
    - libgcrypt-devel
    - libpwquality-devel
    - libssh-devel
    - cyrus-sasl-devel
  labels:
    - eln
    - c10s
