document: feedback-pipeline-workload
version: 1
data:
  name: edge packages
  description: Packages for edge usecases
  maintainer: rhel-sst-edge
  packages:
    - libgpiod
    - libgpiod-c++
    - libgpiod-devel
    - libgpiod-utils
    - python3-libgpiod
    - libi2cd
    - libi2cd-devel
    # Packages co-maintained with the CoreOS SST
    - coreos-installer
    - coreos-installer-bootinfra
    - coreos-installer-dracut
    - ignition
    - ignition-edge
    - nss-altfiles
    - ostree
    - rpm-ostree
  arch_packages:
    aarch64:
      - clevis-pin-tpm2
      - fdo-client
      - fdo-init
      - fdo-manufacturing-server
      - fdo-owner-cli
      - fdo-owner-onboarding-server
      - fdo-rendezvous-server
      - go-fdo-client
      - go-fdo-server
      - go-fdo-server-manufacturer
      - go-fdo-server-owner
      - go-fdo-server-rendezvous
      - greenboot
      - greenboot-default-health-checks
    x86_64:
      - clevis-pin-tpm2
      - fdo-client
      - fdo-init
      - fdo-manufacturing-server
      - fdo-owner-cli
      - fdo-owner-onboarding-server
      - fdo-rendezvous-server
      - go-fdo-client
      - go-fdo-server
      - go-fdo-server-manufacturer
      - go-fdo-server-owner
      - go-fdo-server-rendezvous
      - greenboot
      - greenboot-default-health-checks
    ppc64le:
      - greenboot
      - greenboot-default-health-checks
  labels:
    - eln
    - c10s
