document: feedback-pipeline-workload
version: 1
data:
  name: RHEL Image Azure
  description: Packages in the RHEL Image Azure
  maintainer: tdawson@redhat.com
  labels:
    - eln
    - c10s
  arch_packages:
    aarch64:
      - NetworkManager
      - NetworkManager-cloud-setup
      - NetworkManager-tui
      - PackageKit
      - WALinuxAgent
      - acl
      - amd-gpu-firmware
      - at
      - attr
      - audit
      - authselect
      - basesystem
      - bash
      - bash-color-prompt
      - bash-completion
      - bc
      - blktrace
      - bluez
      - bpftool
      - bzip2
      - chrony
      - cloud-init
      - cloud-utils-growpart
      - cockpit
      - cockpit-bridge
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
      - coreutils
      - cpio
      - cronie
      - crontabs
      - crypto-policies
      - crypto-policies-scripts
      - cryptsetup
      - curl
      - cyrus-sasl-plain
      - dbus
      - dnf
      - dnf-plugins-core
      - dos2unix
      - dosfstools
      - dracut-config-generic
      - e2fsprogs
      - ed
      - efibootmgr
      - ethtool
      - file
      - filesystem
      - glibc
      - gnupg2
      - grub2-efi-aa64
      - grub2-tools
      - grubby
      - hostname
      - hyperv-daemons
      - initscripts-rename-device
      - insights-client
      - intel-gpu-firmware
      - iproute
      - iproute-tc
      - iputils
      - irqbalance
      - kbd
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-tools
      - kexec-tools
      - kpatch
      - kpatch-dnf
      - langpacks-en
      - ledmon
      - less
      - libertas-firmware
      - libstoragemgmt
      - libsysfs
      - linux-firmware
      - logrotate
      - lshw
      - lsof
      - lsscsi
      - lvm2
      - mailcap
      - man-db
      - man-pages
      - mdadm
      - mtr
      - nano
      - ncurses
      - net-tools
      - netronome-firmware
      - nmap-ncat
      - nvidia-gpu-firmware
      - nvme-cli
      - openssh-clients
      - openssh-server
      - p11-kit
      - parted
      - patch
      - pciutils
      - plocate
      - policycoreutils
      - polkit
      - prefixdevname
      - procps-ng
      - psacct
      - python3-libselinux
      - quota
      - realmd
      - redhat-release
      - redhat-release-eula
      - rhc
      - rng-tools
      - rootfiles
      - rpm
      - rpm-plugin-audit
      - rsync
      - rsyslog
      - rsyslog-gnutls
      - rsyslog-gssapi
      - rsyslog-relp
      - selinux-policy-targeted
      - setup
      - sg3_utils
      - sg3_utils-libs
      - shadow-utils
      - shim-aa64
      - smartmontools
      - sos
      - sscg
      - sssd
      - sssd-common
      - sssd-kcm
      - strace
      - sudo
      - symlinks
      - system-reinstall-bootc
      - systemd
      - systemd-udev
      - tar
      - tcpdump
      - time
      - tree
      - tuned
      - unzip
      - usbutils
      - util-linux
      - uuid
      - vim-enhanced
      - vim-minimal
      - virt-what
      - wget
      - which
      - words
      - xfsdump
      - xfsprogs
      - yum
      - yum-utils
      - zip
    x86_64:

      - NetworkManager
      - NetworkManager-cloud-setup
      - NetworkManager-tui
      - PackageKit
      - WALinuxAgent
      - acl
      - amd-gpu-firmware
      - at
      - attr
      - audit
      - authselect
      - basesystem
      - bash
      - bash-color-prompt
      - bash-completion
      - bc
      - blktrace
      - bluez
      - bpftool
      - bzip2
      - chrony
      - cloud-init
      - cloud-utils-growpart
      - cockpit
      - cockpit-bridge
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
      - coreutils
      - cpio
      - cronie
      - crontabs
      - crypto-policies
      - crypto-policies-scripts
      - cryptsetup
      - curl
      - cyrus-sasl-plain
      - dbus
      - dnf
      - dnf-plugins-core
      - dos2unix
      - dosfstools
      - dracut-config-generic
      - e2fsprogs
      - ed
      - efibootmgr
      - ethtool
      - file
      - filesystem
      - fprintd-pam
      - glibc
      - gnupg2
      - grub2-efi-x64
      - grub2-pc
      - grubby
      - hostname
      - hyperv-daemons
      - initscripts-rename-device
      - insights-client
      - intel-gpu-firmware
      - iproute
      - iproute-tc
      - iputils
      - irqbalance
      - iwlwifi-dvm-firmware
      - iwlwifi-mvm-firmware
      - kbd
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-tools
      - kexec-tools
      - kpatch
      - kpatch-dnf
      - langpacks-en
      - ledmon
      - less
      - libertas-firmware
      - libstoragemgmt
      - libsysfs
      - linux-firmware
      - logrotate
      - lshw
      - lsof
      - lsscsi
      - lvm2
      - mailcap
      - man-db
      - man-pages
      - mcelog
      - mdadm
      - microcode_ctl
      - mtr
      - nano
      - ncurses
      - net-tools
      - netronome-firmware
      - nmap-ncat
      - nvidia-gpu-firmware
      - nvme-cli
      - openssh-clients
      - openssh-server
      - p11-kit
      - parted
      - patch
      - pciutils
      - plocate
      - policycoreutils
      - polkit
      - prefixdevname
      - procps-ng
      - psacct
      - python3-libselinux
      - quota
      - realmd
      - redhat-release
      - redhat-release-eula
      - rhc
      - rng-tools
      - rootfiles
      - rpm
      - rpm-plugin-audit
      - rsync
      - rsyslog
      - rsyslog-gnutls
      - rsyslog-gssapi
      - rsyslog-relp
      - selinux-policy-targeted
      - setup
      - sg3_utils
      - sg3_utils-libs
      - shadow-utils
      - shim-x64
      - smartmontools
      - sos
      - sscg
      - sssd
      - sssd-common
      - sssd-kcm
      - strace
      - sudo
      - symlinks
      - system-reinstall-bootc
      - systemd
      - systemd-udev
      - tar
      - tcpdump
      - time
      - tree
      - tuned
      - unzip
      - usbutils
      - util-linux
      - uuid
      - vim-enhanced
      - vim-minimal
      - virt-what
      - wget
      - which
      - words
      - xfsdump
      - xfsprogs
      - yum
      - yum-utils
      - zip
