document: feedback-pipeline-workload
version: 1
data:
  name: RHEL on Microsoft Azure
  description: Userspace agents and tools to assist running RHEL as a guest on Microsoft Azure
  maintainer: rhel-sst-virtualization-cloud
  packages:
    - cloud-init
    - cloud-utils-growpart
    - WALinuxAgent
    - WALinuxAgent-udev
  labels:
    - eln
    - c10s
  arch_packages:    
    x86_64:
      - azure-vm-utils
    aarch64:
      - azure-vm-utils
