document: feedback-pipeline-unwanted
version: 1
data:
  name: Core Services Bootloaders - Blocked packages
  description: Core Services Bootloaders - Packages which should not be in ELN
  maintainer: rhel-sst-cs-bootloaders
  unwanted_source_packages:
    # Replaced by fwupd
    - fwupdate
    - libjaylink
    - libconfuse
    - libftdi
    - dbxtool
  labels:
    - eln
    - c10s
