document: feedback-pipeline-workload
version: 1
data:
  name: bolt
  description: System daemon to manage Thunderbolt devices
  maintainer: rhel-sst-display-hardware-multimedia
  packages:
    - bolt
  labels:
    - eln
    - c10s
