document: feedback-pipeline-workload
version: 1
data:
  name: RHEL on public and private clouds
  description: Userspace agents and tools to assist running RHEL as a guest on public and private clouds
  maintainer: rhel-sst-virtualization_cloud
  packages:
    - cloud-init
    - cloud-utils-growpart
  labels:
    - eln
    - c10s
