document: feedback-pipeline-workload
version: 1
data:
  name: Network Management
  description: >
    Tools for Network Management around NetworkManager.

  maintainer: rhel-sst-network-management
  packages:
    # Core
    - NetworkManager
    - NetworkManager-tui
    # Cellular Modem
    - ModemManager
    - ModemManager-glib
    - NetworkManager-ppp
    - NetworkManager-wwan
    - mobile-broadband-provider-info
    # VPN
    - NetworkManager-libreswan
    - NetworkManager-libreswan-gnome
    # Wifi
    - NetworkManager-wifi
    - wpa_supplicant
    # Bluetooh
    - NetworkManager-bluetooth
    # Server
    # Open vSwitch
    - NetworkManager-ovs
    - nmstate-plugin-ovsdb
    # MACSec / 802.1x
    - wpa_supplicant
    # ADSL
    - NetworkManager-adsl
    # Config files
    - NetworkManager-config-connectivity-redhat
    - NetworkManager-config-server
    # Other
    - NetworkManager-cloud-setup
    - nmstate
    # Development
    - NetworkManager-libnm-devel
    - ModemManager-devel
    - ModemManager-glib-devel
    # GUI
    - network-manager-applet
    - nm-connection-editor
  labels:
    - eln
    - c10s
