document: feedback-pipeline-workload
version: 1
data:
  name: System management
  description: Packages for managing Linux system
  maintainer: rhel-sst-cs-base-utils
  packages:
    - acl
    - attr
    - basesystem
    - bc
    - coreutils
    - environment-modules
    - dcraw
    - diffstat
    - diffutils
    - dos2unix
    - eigen3-devel
    - findutils
    - freeipmi
    - freeipmi-devel
    - gperf
    - ipmitool
    - jasper-devel
    - less
    - libgphoto2-devel
    - librabbitmq
    - librabbitmq-devel
    - libsmi
    - libsndfile
    - libsndfile-devel
    - libva
    - libva-devel
    - lynx
    - mksh
    - netpbm-devel
    - netpbm-doc
    - netpbm-progs
    - opencryptoki
    - opencryptoki-devel
    - opencryptoki-icsftok
    - opencryptoki-libs
    - opencryptoki-swtok
    - OpenIPMI
    - OpenIPMI-devel
    - openwsman-server
    - passwd
    - patch
    - patchutils
    - python3-volume_key
    - rootfiles
    - sblim-cmpi-base
    - sblim-indication_helper
    - sblim-sfcb
    - sblim-sfcc-devel
    - sblim-wbemcli
    - sgpio
    - symlinks
    - sysstat
    - time
    - tmpwatch
    - usermode
    - uuid
    - uuid-devel
    - volume_key
    - volume_key-devel
    - volume_key-libs
    - which
    - wsmancli
    - zsh
    - mpfr
    - mpfr-devel
    - openexr
    - openexr-devel
    - openexr-libs
    - imath
    - imath-devel
    - python3-imath
    - watchdog
  arch_packages:
    #setserial not supported on s390x
    aarch64:
      - setserial
    x86_64:
      - setserial
      - opencryptoki-ccatok
    ppc64le:
      - iprutils
      - setserial
      - powerpc-utils
      - powerpc-utils-core
      - ppc64-diag
      - ppc64-diag-rtas
      - libvpd
      - libvpd-devel
      - lsvpd
      - libservicelog
      - libservicelog-devel
      - librtas
      - librtas-devel
      - servicelog
      - opencryptoki-ccatok
    s390x:
      - opencryptoki-ccatok
      - opencryptoki-ep11tok
      - opencryptoki-icatok
  package_placeholders:
    - srpm_name: rhel-system-roles-sap
      rpms:
        - rpm_name: rhel-system-roles-sap
          description: system roles for SAP
          dependencies: []
          limit_arches:
            - x86_64
            - ppc64le
  labels:
    - eln
    - c10s
