document: feedback-pipeline-workload
version: 1
data:
  name: Apache Subversion
  description: Apache Subversion version control
  maintainer: rhel-sst-cs-net-perf-services
  packages:
    - subversion
    - mod_dav_svn
    - subversion-tools
    - python3-subversion
    - subversion-devel
    - subversion-gnome
    - subversion-perl
  labels:
    - eln
    - c10s
