document: feedback-pipeline-unwanted
version: 1
data:
  name: Ceph storage unwanted
  description: Unwanted Ceph storage packages
  maintainer: rhel-sst-rh-ceph-storage
  unwanted_packages:
    - ceph
    - ceph-base
    - ceph-common
    - ceph-fuse
    - ceph-immutable-object-cache
    - ceph-mds
    - ceph-mgr
    - ceph-mon
    - ceph-osd
    - ceph-radosgw
    - ceph-resource-agents
    - ceph-selinux
    - ceph-test
    - cephadm
    - cephfs-java
    - cephfs-shell
    - libcephfs-devel
    - libcephfs2
    - libcephfs_jni-devel
    - libcephfs_jni1
    - libradosstriper-devel
    - libradosstriper1
    - librgw-devel
    - librgw2
    - python3-ceph-argparse
    - python3-ceph-common
    - python3-cephfs
    - python3-rados
    - python3-rbd
    - python3-rgw
    - rados-objclass-devel
    - rbd-fuse
    - rbd-mirror
    - rbd-nbd
    - ceph-grafana-dashboards
    - ceph-mgr-cephadm
    - ceph-mgr-dashboard
    - ceph-mgr-diskprediction-cloud
    - ceph-mgr-diskprediction-local
    - ceph-mgr-k8sevents
    - ceph-mgr-modules-core
    - ceph-mgr-rook
    - ceph-prometheus-alerts
  labels:
    - eln
    - c10s
