document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted Python 3 packages for ELN
  description: Packages we do not want to ship for Python 3 in RHEL 11+
  maintainer: rhel-sst-pt-python-ruby-nodejs
  # See also rhel-sst-pt-python-ruby-nodejs--unwanted-python3.yaml, this only extends the set
  unwanted_packages:
    # older Python versions
    - python3.12
    - python3.12-libs
  # components for the above
  unwanted_source_packages:
    - python3.12
  labels:
    - eln
