document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted Python 3 packages for ELN
  description: Packages we do not want to ship for Python 3 in RHEL 11+
  maintainer: rhel-pt-python
  # See also rhel-pt-python--unwanted-python3.yaml, this only extends the set
  unwanted_source_packages:
    # older Python versions
    - python3.12
    - python3.13
    # other packages
    - python-wheel
  labels:
    - eln
