document: feedback-pipeline-workload
version: 1
data:
  name: CoreOS
  description: >
    OS compontents for CoreOS based systems. This should be distributed via bootable container images.

  maintainer: rhel-sst-rhcos
  packages:
    - afterburn
    - afterburn-dracut
    - bootupd
    - butane
    - console-login-helper-messages-issuegen
    - console-login-helper-messages-motdgen
    - console-login-helper-messages-profile
    - ignition
    - ignition-validate
    - ssh-key-dir
    # Packages co-maintained with the Edge SST
    - ostree
    - rpm-ostree
    - nss-altfiles
    - coreos-installer
    - coreos-installer-bootinfra
    - coreos-installer-dracut
  labels:
    - eln
    - c10s
