document: feedback-pipeline-workload
version: 1
data:
  name: Web Console (Cockpit)
  description: Cockpit basic packages
  maintainer: rhel-sst-cockpit
  labels:
    - eln
  packages:
    # meta-package for the basic stuff (web server, bridge, core pages)
    - cockpit
    # recommended packages from cockpit metapackage
    - cockpit-storaged
    - cockpit-doc
    # extensions maintained by Cockpit team
    - cockpit-files
  arch_packages:
    aarch64:
      # extensions maintained by Cockpit team
      - cockpit-machines
    s390x:
      # extensions maintained by Cockpit team
      - cockpit-machines
    x86_64:
      # extensions maintained by Cockpit team
      - cockpit-machines
