document: feedback-pipeline-workload
version: 1
data:
  name: PostgreSQL extensions
  description: Server extensions for PostgreSQL
  maintainer: rhel-sst-cs-databases
  packages:
    - pgaudit
    - pg_repack
    - pgvector
    - postgres-decoderbufs
    - postgis
    - postgis-client
    - postgis-docs
    - postgis-upgrade
    - postgis-utils
  labels:
    - eln
    - c10s
