document: feedback-pipeline-workload
version: 1
data:
  name: Bluefield
  description: Packages required for Mellanox Bluefield SmartNIC
  maintainer: rhel-sst-network-drivers
  packages: []
  arch_packages:
    aarch64:
      - rshim
  labels:
    - eln
    - c10s
