document: feedback-pipeline-workload
version: 1
data:
  name: perl-DBD-MySQL:4.050 module
  description: Perl client for MySQL
  maintainer: rhel-sst-cs-stacks
  labels:
    - eln
    - c10s
  packages:
    - perl-DBD-MySQL
