document: feedback-pipeline-workload
version: 1
data:
  name: SCM
  description: Pupular source-management tools
  maintainer: rhel-sst-cs-base-utils
  packages:
    - git
    - git-all
    - git-daemon
    - git-gui
    - git-lfs
    - gitk
  labels:
    - eln
    - c10s
