document: feedback-pipeline-workload
version: 1
data:
  name: Valkey persistent key-value database
  description: CS Stacks - Valkey
  maintainer: rhel-sst-cs-stacks
  packages:
    - valkey
    - valkey-devel
  labels:
    - eln
    - c10s
