document: feedback-pipeline-workload
version: 1
data:
  name: System-wide crypto policies
  description: Configuration and tools providing system-wide crypto policy support
  maintainer: rhel-sst-security-crypto
  packages:
    - crypto-policies
    - crypto-policies-pq-preview
    - crypto-policies-scripts
    - grubby
  labels:
    - eln
    - c10s
