document: feedback-pipeline-workload
version: 1
data:
  name: Storage IO
  description: SST Storage-IO Supported Packages
  maintainer: rhel-sst-storage-io
  packages:
    # Block Storage
    - cxl-cli
    - cxl-devel
    - cxl-libs
    - daxctl
    - daxctl-devel
    - daxctl-libs
    - libaio
    - libaio-devel
    - liburing
    - liburing-devel
    - ndctl
    - ndctl-devel
    - ndctl-libs
    # target
    - python3-configshell
    - python3-kmod
    - python3-pyparsing
    - python3-rtslib
    - targetcli
    # iscsi
    - iscsi-initiator-utils
    - iscsi-initiator-utils-iscsiuio
    - isns-utils
    - isns-utils-libs
    - python3-iscsi-initiator-utils
    # fcoe offload
    - fcoe-utils
    # nvme
    - nvmetcli
    - nvme-cli
    - libnvme
  arch_packages:
    s390x:
      - libblockdev-s390
  labels:
    - eln
    - c10s
