document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted packages for Java
  description: Packages we do not want to ship for Java
  maintainer: rhel-sst-cs-base-utils
  unwanted_source_packages:
    - ant-contrib
    - apache-commons-lang
    - apache-ivy
    - bsh
    - cal10n
    - dom4j
    - forge-parent
    - hamcrest2
    - hsqldb
    - isorelax
    - jakarta-commons-httpclient
    - jakarta-el
    - jakarta-interceptors
    - jakarta-json
    - jakarta-persistence
    - jakarta-saaj
    - jakarta-server-pages
    - jakarta-ws-rs
    - jakarta-xml-rpc
    - jakarta-xml-ws
    - javamail
    - javassist
    - jaxen
    - jboss-modules
    - jmock
    - jtidy
    - log4j12
    - maven-artifact-resolver
    - maven-clean-plugin
    - maven-doxia
    - maven-doxia-sitetools
    - maven-install-plugin
    - maven-invoker
    - maven-invoker-plugin
    - maven-javadoc-plugin
    - maven-mapping
    - maven-reporting-api
    - maven-reporting-impl
    - maven-script-interpreter
    - munge-maven-plugin
    - objectweb-pom
    - os-maven-plugin
    - plexus-build-api
    - plexus-component-api
    - plexus-i18n
    - plexus-velocity
    - sonatype-oss-parent
    - spec-version-maven-plugin
    - spice-parent
    - weld-parent
    - xml-maven-plugin
  labels:
    - eln
    - c10s
