document: feedback-pipeline-workload
version: 1
data:
  name: Node.js runtime â€“ default stream
  description: Node.js (Javascript) runtime and NPM installer for application development
  maintainer: rhel-pt-ruby-nodejs
  packages:
    - nodejs
    - nodejs-devel
    - nodejs-npm
  labels:
    - eln
    - c10s
