document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted packages for CEE Support
  description: Packages not shipping in RHEL 9
  maintainer: rhel-sst-cee-supportability
  unwanted_packages:
    - rhel-tools-container
    - sos-collector
    - redhat-support-lib-python
    - redhat-support-tool
  labels:
    - eln
    - c10s
