document: feedback-pipeline-unwanted
version: 1
data:
  name: .NET Unwanted Packages
  description: Packages that .NET maintainers do not wish to maintain in RHEL 11
  maintainer: rhel-pt-dotnet
  labels:
    - eln
  unwanted_packages:
    # We do not want to ship .NET Core 3.1 which will be EOL by late 2022
    - dotnet-sdk-3.1
    - dotnet-runtime-3.1
    - aspnetcore-runtime-3.1
    # We do not want to ship .NET 5.0 which will be EOL by early 2022
    - dotnet-sdk-5.0
    - dotnet-runtime-5.0
    - aspnetcore-runtime-5.0
    # We do not want to ship .NET 6.0 which will be EOL by late 2024
    - dotnet-sdk-6.0
    - dotnet-runtime-6.0
    - aspnetcore-runtime-6.0
    # We do not want to ship .NET 7.0 which will be EOL by mid 2024
    - dotnet-sdk-7.0
    - dotnet-runtime-7.0
    - aspnetcore-runtime-7.0
    # We do not want to ship .NET 8.0 which will be EOL by late 2026
    - dotnet-sdk-8.0
    - dotnet-runtime-8.0
    - aspnetcore-runtime-8.0
    # We do not want to ship .NET 9.0 which will be EOL by late 2026
    - dotnet-sdk-9.0
    - dotnet-runtime-9.0
    - aspnetcore-runtime-9.0
