document: feedback-pipeline-workload
version: 1
data:
  name: redfish-finder
  description: Utility to receive RAS error tracings
  maintainer: rhel-sst-kernel-ft
  packages: []
  labels:
    - eln
    - c10s
  # package is noarch, but is only useful on and shipped for X86 and ARM
  arch_packages:
    x86_64:
      - redfish-finder
    aarch64:
      - redfish-finder
