document: feedback-pipeline-workload
version: 1
data:
  name: efibootmgr
  description: EFI Boot Manager
  maintainer: rhel-sst-cs-bootloaders
  packages: []
  labels:
    - eln
    - c10s
  arch_packages:
    aarch64:
      - efibootmgr
    x86_64:
      - efibootmgr
