document: feedback-pipeline-workload
version: 1
data:
  name: RHEL Image EC2 HA
  description: Packages in the RHEL Image EC2 HA
  maintainer: bstinson
  labels:
    - eln
  arch_packages:
    x86_64:
      - NetworkManager
      - NetworkManager-cloud-setup
      - NetworkManager-tui
      - amd-gpu-firmware
      - audit
      - authselect
      - basesystem
      - bash
      - chrony
      - cloud-init
      - cloud-utils-growpart
      - coreutils
      - cronie
      - crypto-policies
      - crypto-policies-scripts
      - curl
      - dhcpcd
      - dnf5
      - dnf5-plugins
      - dnf-utils
      - dosfstools
      - dracut-config-generic
      - e2fsprogs
      - efibootmgr
      - fence-agents-all
      - filesystem
      - glibc
      - grub2
      - grub2-efi-x64
      - grub2-pc
      - grubby
      - hostname
      - initscripts-rename-device
      - insights-client
      - intel-gpu-firmware
      - iproute
      - iproute-tc
      - iputils
      - irqbalance
      - iwlwifi-dvm-firmware
      - iwlwifi-mvm-firmware
      - kbd
      - kernel
      - kernel-tools
      - kexec-tools
      - langpacks-en
      - less
      - libsysfs
      - linux-firmware
      - logrotate
      - lshw
      - lsscsi
      - man-db
      - microcode_ctl
      - ncurses
      - nvidia-gpu-firmware
      - openssh-clients
      - openssh-server
      - p11-kit
      - pacemaker
      - parted
      - pcs
      - policycoreutils
      - prefixdevname
      - procps-ng
      - python3-libselinux
      - redhat-release
      - redhat-release-eula
      - rhc
      - rootfiles
      - rpm
      - rpm-plugin-audit
      - rsync
      - rsyslog
      - selinux-policy-targeted
      - setup
      - sg3_utils
      - sg3_utils-libs
      - shadow-utils
      - shim-x64
      - sssd-common
      - sssd-kcm
      - sudo
      - system-reinstall-bootc
      - systemd
      - tar
      - tuned
      - util-linux
      - vim-minimal
      - xfsprogs
      - xfsprogs
