document: feedback-pipeline-workload
version: 1
data:
  name: Application Whitelisting
  description: Packages providing application whitelisting functionality
  maintainer: rhel-security-selinux
  packages:
    - fapolicyd
    - fapolicyd-selinux
  labels:
    - eln
    - c10s
