document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted packages from CS Databases SST
  description: Packages we do not want to ship for CS Databases SST
  maintainer: rhel-sst-cs-databases
  unwanted_packages:
    - libdb-devel # Deprecated in RHEL9
    - libdb
    # Pcre is deprecated and unsupported by upstream since Fedora 38
    - pcre
    - pcre-devel
    - pcre-cpp
    # There are better alternatives than aspell
    # https://fedoraproject.org/wiki/Changes/AspellDeprecation
    - aspell
    - aspell-devel
  labels:
    - eln
    - c10s
