document: feedback-pipeline-workload
version: 1
data:
  name: sysfsutils
  description: Utilities for interfacing with sysfs
  maintainer: rhel-sst-cs-base-utils
  packages:
    - glibc
    - libsysfs
  labels:
    - eln
    - c10s

