document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted Packages - sst_kernel_tps
  description: Packages not shipping in RHEL 9
  maintainer: rhel-sst-kernel-tps (vdronov for rtl-sdr*)
  unwanted_packages:
    - rtl-sdr
    - rtl-sdr-devel
  labels:
    - eln
    - c10s
