document: feedback-pipeline-workload
version: 1
data:
  name: binutils/annobin
  description: Set of packages that GCC depends on
  maintainer: rhel-sst-pt-gcc
  packages:
    - binutils
    - binutils-devel
    - annobin-annocheck
    - annobin-plugin-gcc
  labels:
    - eln
    - c10s
