document: feedback-pipeline-workload
version: 1
data:
    name: Hesiod
    description: Compat packages for the Hesiod system
    maintainer: ssg_idm
    
    packages: []

    labels:
        - c9s

    package_placeholders:
        compat-hesiod:
            description: The Hesiod naming service
            requires: []
            buildrequires:
                - autoconf
                - automake
                - libtool
                - libidn2-devel
            srpm: hesiod
