document: feedback-pipeline-workload
version: 1
data:
  name: FreeRADIUS Server
  description: An open source implementation of RADIUS, the IETF protocol for AAA (Authorisation, Authentication, and Accounting).
  maintainer: ssg_idm
  packages:
    - freeradius
  labels:
    - eln
    - c9s
