document: feedback-pipeline-workload
version: 1
data:
  name: FreeIPA Server - minimal
  description: FreeIPA server
  maintainer: ssg_idm
  packages:
    - ipa-server
    - ipa-selinux # rich dependency that is otherwise unmet
  labels:
    - eln
    - c10s
