document: feedback-pipeline-workload
version: 1
data:
  name: FreeRADIUS Server
  description: An open source implementation of RADIUS, the IETF protocol for AAA (Authorisation, Authentication, and Accounting).
  maintainer: ssg_idm
  packages:
    - freeradius
    - freeradius-devel
    - freeradius-doc
    - freeradius-ldap
    - freeradius-krb5
    - freeradius-utils
    - python3-freeradius
  labels:
    - eln
    - c9s
    - c10s
