document: feedback-pipeline-workload
version: 1
data:
  name: IdM Web Extensions
  description: Specific Apache extensions that are required for client web server IdM experience, whether it is authentication, authorization or extended identity operation
  maintainer: ssg_idm

  packages:
  - mod_auth_gssapi
  - mod_auth_mellon
  - mod_auth_openidc
  - mod_authnz_pam
  - mod_intercept_form_submit
  - mod_lookup_identity
  - keycloak-httpd-client-install

  labels:
  - c9s
