document: feedback-pipeline-workload
version: 1
data:
  name: C Development Environment
  description: A C development environment.
  maintainer: ssg_platform_tools

  packages:
  # The minimum development environment is this:
  - gcc
  - binutils
  - glibc
  - glibc-common
  - glibc-devel
  # Full development includes additional packages:
  - glibc-utils
  - glibc-static
  - glibc-nss-devel
  # Support all locales.
  - glibc-all-langpacks

  labels:
  - eln
  - c9s
