document: feedback-pipeline-workload
version: 1
data:
  name: binutils/annobin
  description: Set of packages that GCC depends on
  maintainer: ssg_platform_tools

  packages:
  - binutils
  - binutils-devel
  - binutils-gold
  - annobin
  - annobin-annocheck

  labels:
  - eln
  - c9s
