document: feedback-pipeline-workload
version: 1
data:
  name: perl-XML-Simple
  description: Easy API to maintain XML in Perl
  maintainer: sst_cs_apps
  packages:
    - perl-XML-Simple
  labels:
    - eln
    - c10s
