document: feedback-pipeline-workload
version: 1
data:
  name: Virtualization on RHEL - KVM Userspace
  description: Userspace agents and tools that enable virtualization capabilities on RHEL
  maintainer: sst_virtualization
  packages:
    - augeas
    - dtc
    - gtk-vnc2
    - hexedit
    - hivex
    - ipxe-roms-qemu
    - ksmtuned
    - libiscsi
    - libnbd
    - libosinfo
    - libvirt
    - libvirt-dbus
    - libvirt-glib
    - mdevctl
    - nbdkit
    - osinfo-db
    - osinfo-db-tools
    - python-augeas
    - python3-libvirt
    - python3-pefile
    - python3-virt-firmware
    - spice-protocol
    - spice-vdagent
    - uki-direct
    - vhostmd
    - virt-install
    - virt-viewer
    - virt-what
  labels:
    - c9s
  arch_packages:
    x86_64:
      - edk2-ovmf
      - guestfs-tools
      - libguestfs
      - libguestfs-inspect-icons
      - libguestfs-winsupport
      - libpmem
      - qemu-kvm
      - seabios
      - sevctl
      - sgabios
      - supermin
      - virt-p2v
      - virt-top
      - virt-v2v
    ppc64le:
      - libpmem
      - powerpc-utils
    aarch64:
      - edk2-aarch64
      - guestfs-tools
      - libguestfs
      - libguestfs-inspect-icons
      - qemu-kvm
      - supermin
      - virt-top
    s390x:
      - guestfs-tools
      - libguestfs
      - libguestfs-inspect-icons
      - qemu-kvm
      - supermin
      - virt-top
