document: feedback-pipeline-workload
version: 1
data:
  name: Graphical toolkits
  description: GUI toolkits like e.g. Tk, wxWidgets, etc.
  maintainer: sst_cs_infra_services

  packages:
  - tk

  labels:
  - eln
  - c9s
