document: feedback-pipeline-workload
version: 1
data:
  name: Python GSSAPI
  description: Tools for using GSSAPI in Python applications
  maintainer: sst_identity_management

  packages:
  - python3-gssapi
  - python3-requests-gssapi
  - python3-urllib-gssapi

  labels:
  - eln
  - c9s
