document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Font Viewer
  description: Application for viewing available fonts on Workstation
  maintainer: sst_desktop

  packages:
  - gnome-font-viewer

  labels:
  - eln
  - c9s
