document: feedback-pipeline-workload
version: 1
data:
  name: Subscripiton Manager
  description: Manages subscriptions and yum repositories.
  maintainer: sst_subscription_manager

  packages:
    - libdnf-plugin-subscription-manager
    - python3-subscription-manager-rhsm
    - subscription-manager
    - subscription-manager-cockpit
    - subscription-manager-plugin-ostree
    - subscription-manager-rhsm-certificates
  
  labels:
  - eln
  - c9s
