document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted Debuggers packages
  description: Unwanted Debuggers packages
  maintainer: sst_pt_perf_debug

  unwanted_packages:
  - babeltrace

  unwanted_arch_packages:
    i686:
    - gdb-minimal

  labels:
  - eln
  - c9s
