document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Classic session
  description: GNOME Classic session
  maintainer: sst_desktop_platform_technologies
  packages:
    - gnome-classic-session
    - gnome-shell-extension-apps-menu
    - gnome-shell-extension-places-menu
    - gnome-shell-extension-launch-new-instance
    - gnome-shell-extension-window-list
  labels:
    - eln
    - c10s
  package_placeholders:
    # Extensions no longer packaged in Fedora
    - srpm_name: gnome-shell-extensions
      rpms:
        - rpm_name: gnome-shell-extension-desktop-icons
          description: This GNOME Shell extension adds desktop icons support as seen in GNOME 2
          dependencies:
            - gnome-shell-extension-common
        - rpm_name: gnome-shell-extension-top-icons
          description: This GNOME Shell extension moves legacy tray icons into the top bar
          dependencies:
            - gnome-shell-extension-common
