document: feedback-pipeline-workload
version: 1
data:
  name: GNOME System Monitor
  description: Default system monitor application for Workstation
  maintainer: sst_desktop

  packages:
  - gnome-system-monitor

  labels:
  - eln
  - c9s
