document: feedback-pipeline-workload
version: 1
data:
  name: Ruby runtime
  description: Ruby interpretter and the most basic libraries
  maintainer: sst_cs_apps

  packages:
  - ruby
  - ruby-default-gems
  - ruby-devel
  - ruby-libs
  - rubygem-bigdecimal
  - rubygem-bundler
  - rubygem-io-console
  - rubygem-irb
  - rubygem-json
  - rubygem-minitest
  - rubygem-power_assert
  - rubygem-psych
  - rubygem-rake
  - rubygem-rbs
  - rubygem-rdoc
  - rubygem-rexml
  - rubygem-rss
  - rubygem-test-unit
  - rubygem-typeprof
  - rubygems
  - rubygems-devel
  - rubygem-abrt

  labels:
  - eln
  - c9s
