document: feedback-pipeline-workload
version: 1
data:
  name: Other packages from SST CS Aps for ELN
  description: Unsorted tools owned by CS Apps SST
  maintainer: sst_cs_apps
  packages:
    - pcre2
    - pcre2-devel
    - pcre2-tools
  labels:
    - eln
    - c10s
