document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted packages from CS Apps SST
  description: Packages we do not want to ship for CS Apps SST
  maintainer: sst_cs_apps
  unwanted_packages:
    # Pcre is deprecated and unsupported by upstream since Fedora 38
    - pcre
    - pcre-devel
    - pcre-cpp
    # There are better alternatives than aspell
    # https://fedoraproject.org/wiki/Changes/AspellDeprecation
    - aspell
    - aspell-devel
    # Seems like not much wanted
    - python3-pyodbc
  labels:
    - eln
