document: feedback-pipeline-workload
version: 1
data:
  name: Wayland infrastructure
  description: Contains tools and related infrastructure used in a Wayland environment
  maintainer: sst_gpu
  packages:
    - wayland-utils
    - waypipe
    # Needed by the NVIDIA drivers to use Mutter's EGLStreams
    - egl-wayland
    - libinput-utils
    - xwayland-run
    - gnome-ponytail-daemon
  labels:
    - eln
