document: feedback-pipeline-workload
version: 1
data:
  name: opae
  description: User libraries for Intel FPGA's
  maintainer: sst_accelerators

  packages: []

  labels:
  - eln
  - c9s

  arch_packages:
    x86_64:
    - opae
    - opae-devel
