document: feedback-pipeline-workload
version: 1
data:
  name: Python DB connectors
  description: Databases connectors for Python
  maintainer: sst_cs_apps

  packages:
  - python3-PyMySQL
  - python3-psycopg2

  labels:
  - eln
