document: feedback-pipeline-workload
version: 1
data:
  name: I2C tools
  description: Communication with I2C devices. This may include reading data from sensors, communication with EEPROMS, uses in robotics, embedded, IoT devices, industrial automation.
  maintainer: sst_cs_infra_services

  packages: []

  arch_packages:
    armv7hl:
    # i2c-tools (ExcludeArch: s390 s390x)
    - i2c-tools
    - i2c-tools-perl
    - libi2c
    aarch64:
    # i2c-tools (ExcludeArch: s390 s390x)
    - i2c-tools
    - i2c-tools-perl
    - libi2c
    ppc64le:
    # i2c-tools (ExcludeArch: s390 s390x)
    - i2c-tools
    - i2c-tools-perl
    - libi2c
    x86_64:
    # i2c-tools (ExcludeArch: s390 s390x)
    - i2c-tools
    - i2c-tools-perl
    - libi2c

  labels:
  - eln
  - c9s
