document: feedback-pipeline-workload
version: 1
data:
  name: libkeepalive
  description: >
    Allow enabling TCP keepalive on applications that don't allow such
    configuration.
  maintainer: sst_networking_core
  packages:
  - libkeepalive

  labels:
  - eln
  - c9s
