document: feedback-pipeline-workload
version: 1
data:
  name: Eye of GNOME
  description: Default image viewer for Workstation
  maintainer: sst_desktop_applications

  packages:
  - eog

  labels:
  - c9s
