document: feedback-pipeline-workload
version: 1
data:
  name: perl:5.30 module
  description: Perl 5.30
  maintainer: sst_cs_apps
  labels:
  - eln
  packages:
  - perl
  - perl-Algorithm-Diff
  - perl-Archive-Tar
  - perl-Archive-Zip
  - perl-Attribute-Handlers
  - perl-autodie
  - perl-bignum
  - perl-Carp
  - perl-Compress-Bzip2
  - perl-Compress-Raw-Bzip2
  - perl-Compress-Raw-Lzma
  - perl-Compress-Raw-Zlib
  - perl-Config-Perl-V
  - perl-constant
  - perl-CPAN
  - perl-CPAN-DistnameInfo
  - perl-CPAN-Meta
  - perl-CPAN-Meta-Requirements
  - perl-CPAN-Meta-YAML
  - perl-Data-Dumper
  - perl-Data-OptList
  - perl-Data-Section
  - perl-DB_File
  - perl-devel
  - perl-Devel-Peek
  - perl-Devel-PPPort
  - perl-Devel-SelfStubber
  - perl-Devel-Size
  - perl-Digest
  - perl-Digest-MD5
  - perl-Digest-SHA
  - perl-Encode
  - perl-Encode-devel
  - perl-encoding
  - perl-Env
  - perl-Errno
  - perl-experimental
  - perl-Exporter
  - perl-ExtUtils-CBuilder
  - perl-ExtUtils-Command
  - perl-ExtUtils-Embed
  - perl-ExtUtils-Install
  - perl-ExtUtils-MakeMaker
  - perl-ExtUtils-Manifest
  - perl-ExtUtils-Miniperl
  - perl-ExtUtils-MM-Utils
  - perl-ExtUtils-ParseXS
  - perl-Fedora-VSP
  - perl-File-Fetch
  - perl-File-HomeDir
  - perl-File-Path
  - perl-File-Temp
  - perl-File-Which
  - perl-Filter
  - perl-Filter-Simple
  - perl-generators
  - perl-Getopt-Long
  - perl-homedir
  - perl-HTTP-Tiny
  - perl-Importer
  - perl-inc-latest
  - perl-interpreter
  - perl-IO
  - perl-IO-Compress
  - perl-IO-Compress-Lzma
  - perl-IO-Socket-IP
  - perl-IO-Zlib
  - perl-IPC-Cmd
  - perl-IPC-System-Simple
  - perl-IPC-SysV
  - perl-JSON-PP
  - perl-libnet
  - perl-libnetcfg
  - perl-libs
  - perl-local-lib
  - perl-Locale-Maketext
  - perl-Locale-Maketext-Simple
  - perl-macros
  - perl-Math-BigInt
  - perl-Math-BigInt-FastCalc
  - perl-Math-BigRat
  - perl-Math-Complex
  - perl-Memoize
  - perl-MIME-Base64
  - perl-Module-Build
  - perl-Module-CoreList
  - perl-Module-CoreList-tools
  - perl-Module-Load
  - perl-Module-Load-Conditional
  - perl-Module-Loaded
  - perl-Module-Metadata
  - perl-MRO-Compat
  - perl-Net-Ping
  - perl-open
  - perl-Package-Generator
  - perl-Params-Check
  - perl-Params-Util
  - perl-parent
  - perl-PathTools
  - perl-Perl-OSType
  - perl-perlfaq
  - perl-PerlIO-via-QuotedPrint
  - perl-Pod-Checker
  - perl-Pod-Escapes
  - perl-Pod-Html
  - perl-Pod-Parser
  - perl-Pod-Perldoc
  - perl-Pod-Simple
  - perl-Pod-Usage
  - perl-podlators
  - perl-Scalar-List-Utils
  - perl-SelfLoader
  - perl-Socket
  - perl-Software-License
  - perl-Storable
  - perl-Sub-Exporter
  - perl-Sub-Install
  - perl-Sys-Syslog
  - perl-Term-ANSIColor
  - perl-Term-Cap
  - perl-Term-Table
  - perl-Test
  - perl-Test-Harness
  - perl-Test-Simple
  - perl-tests
  - perl-Text-Balanced
  - perl-Text-Diff
  - perl-Text-Glob
  - perl-Text-ParseWords
  - perl-Text-Tabs+Wrap
  - perl-Text-Template
  - perl-Thread-Queue
  - perl-threads
  - perl-threads-shared
  - perl-Time-HiRes
  - perl-Time-Local
  - perl-Time-Piece
  - perl-Unicode-Collate
  - perl-Unicode-Normalize
  - perl-URI
  - perl-utils
  - perl-version
  modules_disable:
  - perl:5.32
  modules_enable:
  - perl:5.30
