document: feedback-pipeline-workload
version: 1
data:
  name: Compression
  description: Tools for file compression
  maintainer: sst_cs_plumbers

  packages:
  - lzop
  - bzip2
  - gzip
  - lz4
  - unzip
  - zip
  - zstd
  - zziplib-utils

  labels:
  - eln
  - c9s
