document: feedback-pipeline-workload
version: 1
data:
  name: C++ Development Environment
  description: A minimal C++ development environment.
  maintainer: sst_pt_gcc
  packages:
    # The minimum development environment is this:
    - gcc
    - gcc-c++
    - binutils
    - glibc
    - glibc-common
    - glibc-devel
    - libstdc++
    - libstdc++-devel
    - libgcc
    # We support only the C/POSIX/C.UTF-8 locales.
    - glibc-minimal-langpack
  labels:
    - eln
    - c9s
