document: feedback-pipeline-workload
version: 1
data:
  name: LibreOffice
  description: Default office suite for Workstation
  maintainer: sst_desktop

  packages:
  - autocorr-af
  - autocorr-bg
  - autocorr-ca
  - autocorr-cs
  - autocorr-da
  - autocorr-de
  - autocorr-en
  - autocorr-es
  - autocorr-fa
  - autocorr-fi
  - autocorr-fr
  - autocorr-ga
  - autocorr-hr
  - autocorr-hu
  - autocorr-is
  - autocorr-it
  - autocorr-ja
  - autocorr-ko
  - autocorr-lb
  - autocorr-lt
  - autocorr-mn
  - autocorr-nl
  - autocorr-pl
  - autocorr-pt
  - autocorr-ro
  - autocorr-ru
  - autocorr-sk
  - autocorr-sl
  - autocorr-sr
  - autocorr-sv
  - autocorr-tr
  - autocorr-vi
  - autocorr-zh
  - libreoffice-filters
  - libreoffice-gdb-debug-support
  - libreoffice-gtk3
  - libreoffice-help-ar
  - libreoffice-help-bg
  - libreoffice-help-bn
  - libreoffice-help-ca
  - libreoffice-help-cs
  - libreoffice-help-da
  - libreoffice-help-de
  - libreoffice-help-dz
  - libreoffice-help-el
  - libreoffice-help-en
  - libreoffice-help-eo
  - libreoffice-help-es
  - libreoffice-help-et
  - libreoffice-help-eu
  - libreoffice-help-fi
  - libreoffice-help-fr
  - libreoffice-help-gl
  - libreoffice-help-gu
  - libreoffice-help-he
  - libreoffice-help-hi
  - libreoffice-help-hr
  - libreoffice-help-hu
  - libreoffice-help-id
  - libreoffice-help-it
  - libreoffice-help-ja
  - libreoffice-help-ko
  - libreoffice-help-lt
  - libreoffice-help-lv
  - libreoffice-help-nb
  - libreoffice-help-nl
  - libreoffice-help-nn
  - libreoffice-help-pl
  - libreoffice-help-pt-BR
  - libreoffice-help-pt-PT
  - libreoffice-help-ro
  - libreoffice-help-ru
  - libreoffice-help-si
  - libreoffice-help-sk
  - libreoffice-help-sl
  - libreoffice-help-sv
  - libreoffice-help-ta
  - libreoffice-help-tr
  - libreoffice-help-uk
  - libreoffice-help-zh-Hans
  - libreoffice-help-zh-Hant
  - libreoffice-langpack-af
  - libreoffice-langpack-ar
  - libreoffice-langpack-as
  - libreoffice-langpack-bg
  - libreoffice-langpack-bn
  - libreoffice-langpack-br
  - libreoffice-langpack-ca
  - libreoffice-langpack-cs
  - libreoffice-langpack-cy
  - libreoffice-langpack-da
  - libreoffice-langpack-de
  - libreoffice-langpack-dz
  - libreoffice-langpack-el
  - libreoffice-langpack-eo
  - libreoffice-langpack-es
  - libreoffice-langpack-et
  - libreoffice-langpack-eu
  - libreoffice-langpack-fa
  - libreoffice-langpack-fi
  - libreoffice-langpack-fr
  - libreoffice-langpack-ga
  - libreoffice-langpack-gl
  - libreoffice-langpack-gu
  - libreoffice-langpack-he
  - libreoffice-langpack-hi
  - libreoffice-langpack-hr
  - libreoffice-langpack-hu
  - libreoffice-langpack-id
  - libreoffice-langpack-it
  - libreoffice-langpack-ja
  - libreoffice-langpack-kk
  - libreoffice-langpack-kn
  - libreoffice-langpack-ko
  - libreoffice-langpack-lt
  - libreoffice-langpack-lv
  - libreoffice-langpack-mai
  - libreoffice-langpack-ml
  - libreoffice-langpack-mr
  - libreoffice-langpack-nb
  - libreoffice-langpack-nl
  - libreoffice-langpack-nn
  - libreoffice-langpack-nr
  - libreoffice-langpack-nso
  - libreoffice-langpack-or
  - libreoffice-langpack-pa
  - libreoffice-langpack-pl
  - libreoffice-langpack-pt-BR
  - libreoffice-langpack-pt-PT
  - libreoffice-langpack-ro
  - libreoffice-langpack-ru
  - libreoffice-langpack-si
  - libreoffice-langpack-sk
  - libreoffice-langpack-sl
  - libreoffice-langpack-sr
  - libreoffice-langpack-ss
  - libreoffice-langpack-st
  - libreoffice-langpack-sv
  - libreoffice-langpack-ta
  - libreoffice-langpack-te
  - libreoffice-langpack-th
  - libreoffice-langpack-tn
  - libreoffice-langpack-tr
  - libreoffice-langpack-ts
  - libreoffice-langpack-uk
  - libreoffice-langpack-ve
  - libreoffice-langpack-xh
  - libreoffice-langpack-zh-Hans
  - libreoffice-langpack-zh-Hant
  - libreoffice-langpack-zu
  - libreoffice-sdk
  - libreoffice-sdk-doc
  - libreoffice-wiki-publisher
  - libreoffice-xsltfilter
  - libreofficekit
  - libreoffice-base
  - libreoffice-calc
  - libreoffice-core
  - libreoffice-data
  - libreoffice-draw
  - libreoffice-emailmerge
  - libreoffice-graphicfilter
  - libreoffice-impress
  - libreoffice-langpack-en
  - libreoffice-math
  - libreoffice-ogltrans
  - libreoffice-opensymbol-fonts
  - libreoffice-pdfimport
  - libreoffice-pyuno
  - libreoffice-ure
  - libreoffice-ure-common
  - libreoffice-writer
  - libreoffice-x11

  labels:
  - eln
  - c9s
