document: feedback-pipeline-workload
version: 1
data:
  name: TigerVNC
  description: VNC server and client for Workstation
  maintainer: sst_desktop_applications

  packages:
  - tigervnc
  - tigervnc-selinux
  - tigervnc-server
  - tigervnc-server-module

  labels:
  - c9s
