document:  feedback-pipeline-workload
version: 1
data:
    name: kernel devel/debug
    description: Kernel packages used for devel/debug
    maintainer: sst_kernel_maintainers
    packages:
        - kernel-cross-headers
        - kernel-headers
        - kernel-devel
        - kernel-tools-libs-devel
    labels:
        - eln
    arch_packages:
        s390x:
            - kernel-zfcpdump-devel

