document: feedback-pipeline-workload
version: 1
data:
  name: realtime perf
  description: Packages for testing realtime performance
  maintainer: sst_kernel_rats

  labels:
  - eln
  - c9s

  arch_packages:
    x86_64:
      - stress-ng

  package_placeholders:
    realtime-tests:
      srpm: realtime-tests
      description: This package is not in Fedora (yet), but we want it here.
      requires:
        - bash
        - bc
      buildrequires:
        - gcc
        - make
        - numactl-devel
        - python3-devel
      limit_arches:
        - x86_64
    rteval:
      srpm: rteval
      description: This package is not in Fedora (yet), but we want it here.
      requires:
        - python3-ethtool
        - python3-lxml
        - python3-dmidecode
        - sysstat
        - xz
        - bzip2
        - kernel-headers
        - sos
        - tar
        - numactl
        - gcc
        - flex
        - bison
        - bc
        - make
        - openssl
        - openssl-devel
#   commented out due to content resolver not liking requires in the
#   placeholder section
#        - rteval-loads
#        - rteval-common
      buildrequires:
        - python3-devel
      limit_arches:
        - x86_64
    rteval-loads:
      srpm: rteval-loads
      description: This package is not in Fedora (yet), but we want it here.
      requires:
        - gcc
        - binutils
        - make
        - kernel-headers
      buildrequires:
        - gcc
        - glibc-devel
        - kernel-headers
        - keyutils-libs-devel
        - libaio-devel
        - libattr-devel
        - libcap-devel
        - lksctp-tools-devel
        - zlib-devel
      limit_arches:
        - x86_64
    rteval-common:
      srpm: rteval
      description: This package is not in Fedora (yet), but we want it here.
      limit_arches:
        - x86_64
