document: feedback-pipeline-workload
version: 1
data:
  name: realtime perf
  description: Packages for testing realtime performance
  maintainer: sst_kernel_rts

  labels:
  - eln
  - c9s

  arch_packages:
    x86_64:
      - realtime-tests
      - rteval
      - rteval-loads
      - stress-ng
