document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted packages for libcgroup
  description: libcgroup doesn't support cgroupv2 and has been effectively dead for a long time
  maintainer: sst_cs_apps

  unwanted_packages:
  - libcgroup

  labels:
  - eln
  - c9s
