document: feedback-pipeline-workload
version: 1
data:
  name: Base userspace - minimal
  description: Basic tools and daemon needed to run a server
  maintainer: sst_cs_plumbers

  packages:
  - coreutils-single
  - curl-minimal
  - libcurl-minimal

  labels:
  - c9s
