---
document: feedback-pipeline-workload
version: 1
data:
  name: post-quantum cryptography
  description: Components providing post-quantum cryptography primitives.
  maintainer: sst_security_crypto
  packages:
    - liboqs
    - oqsprovider
  labels:
    - eln
