document: feedback-pipeline-workload
version: 1
data:
  name: Mail Delivery Agent (MDA)
  description: Software for local delivery and accessing of electronic mail
  maintainer: sst_cs_infra_services
  packages:
    - cyrus-imapd
    - procmail
    - xapian-core
  labels:
    - eln
    - c9s
