document: feedback-pipeline-workload
version: 1
data:
  name: GNU Make
  description: Application build tooling.
  maintainer: sst_pt_libraries

  packages:
  - make
  - make-devel

  labels:
  - eln
  - c9s
