---
document: feedback-pipeline-workload
version: 1
data:
  name: openssl
  description: General purpose cryptographic library and toolkit for TLS and SSL protocols.
  maintainer: sst_security_crypto

  packages:
  - openssl
  - compat-openssl11

  labels:
  - eln
  - c9s

