document:  feedback-pipeline-workload
version: 1
data:
    name: kernel base
    description: Base set of kernel packages and tools to ship
    maintainer: sst_kernel_maintainers
    packages:
        - amd-gpu-firmware
        - amd-ucode-firmware
        - atheros-firmware
        - brcmfmac-firmware
        - cirrus-audio-firmware
        - dvb-firmware
        - intel-audio-firmware
        - intel-gpu-firmware
        - intel-vsc-firmware
        - iwlegacy-firmware
        - iwlwifi-dvm-firmware
        - iwlwifi-mvm-firmware
        - libertas-firmware
        - linux-firmware
        - linux-firmware-whence
        - liquidio-firmware
        - mlxsw_spectrum-firmware
        - mrvlprestera-firmware
        - mt7xxx-firmware
        - netronome-firmware
        - nvidia-gpu-firmware
        - nxpwireless-firmware
        - qcom-firmware
        - realtek-firmware
        - tiwilink-firmware
        - bpftool
        - kernel
        - kernel-abi-stablelists
        - kernel-core
        - kernel-cross-headers
        - kernel-doc
        - kernel-headers
        - kernel-modules
        - kernel-modules-core
        - kernel-modules-extra
        - kernel-tools
        - perf
        - python3-perf
        - rtla
        - rv
    labels:
        - eln
    arch_packages:
        s390x:
            - kernel-zfcpdump
            - kernel-zfcpdump-core
            - kernel-zfcpdump-modules
            - kernel-zfcpdump-modules-extra
        x86_64:
            - kernel-tools-libs
            - kernel-uki-virt
        aarch64:
            - kernel-64k
            - kernel-64k-core
            - kernel-64k-modules
            - kernel-64k-modules-core
            - kernel-64k-modules-extra
            - kernel-64k-uki-virt
            - kernel-tools-libs
            - kernel-uki-virt
        ppc64le:
            - kernel-tools-libs
