document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Software
  description: Default application and updates manager for Workstation
  maintainer: sst_desktop_applications

  packages:
  - gnome-software

  labels:
  - eln
  - c9s
