document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted Performance Co-Pilot and Grafana components
  description: Unwanted Performance Co-Pilot and Grafana components
  maintainer: sst_pt_pcp

  unwanted_packages:
  - parfait
  - pcp-manager
  - pcp-webapi
  - pcp-webapp-blinkenlights
  - pcp-webapp-grafana
  - pcp-webapp-graphite
  - pcp-webapp-vector
  - si-units
  - unit-api
  - uom-lib
  - uom-parent
  - uom-se
  - uom-systems

  labels:
  - eln
  - c9s
