document: feedback-pipeline-workload
version: 1
data:
  name: Platform Storage
  description: Platform Storage Supported Packages
  maintainer: sst_platform_storage

  packages:
    # Stratis
    - python-hs-dbus-signature
    - python3-dbus-client-gen
    - python3-dbus-python-client-gen
    - python3-dbus-signature-pyparsing
    - python3-into-dbus-python
    - python3-justbases
    - python3-justbytes
    - stratis-cli
    - stratisd

    # Block Storage
    - daxctl
    - daxctl-devel
    - daxctl-libs
    - libaio
    - libaio-devel
    - liburing
    - liburing-devel
    - ndctl
    - ndctl-devel
    - ndctl-libs

    # target
    - nvmetcli
    - python3-configshell
    - python3-kmod
    - python3-pyparsing
    - python3-rtslib
    - python3-urwid
    - targetcli

    # iscsi
    - iscsi-initiator-utils
    - iscsi-initiator-utils-iscsiuio
    - isns-utils
    - isns-utils-libs
    - python3-iscsi-initiator-utils

      # fcoe offload
    - fcoe-utils

    # LVM
    # Boom-boot and its sub-packages
    - boom-boot
    - boom-boot-conf
    - boom-boot-grub2
    - python3-boom
    # lvm2 and its sub-packages
    - cryptsetup
    - device-mapper
    - device-mapper-devel
    - device-mapper-event
    - device-mapper-event-devel
    - device-mapper-event-libs
    - device-mapper-libs
    - device-mapper-multipath
    - device-mapper-persistent-data
    - dlm
    - lvm2
    - lvm2-dbusd
    - lvm2-devel
    - lvm2-libs
    - lvm2-lockd
    - mdadm
    - sanlock
    - userspace-rcu
    # sid is pending https://fedoraproject.org/wiki/Changes/SID
    # - sid

    # Storage Management
    - hdparm
    - libblockdev
    - libblockdev-crypto
    - libblockdev-dm
    - libblockdev-fs
    - libblockdev-kbd
    - libblockdev-loop
    - libblockdev-lvm
    - libblockdev-mdraid
    - libblockdev-mpath
    - libblockdev-nvdimm
    - libblockdev-part
    - libblockdev-plugins-all
    - libblockdev-s390 (s390x)
    - libblockdev-swap
    - libblockdev-tools
    - libblockdev-utils
    - libbytesize
    - libstoragemgmt
    - libstoragemgmt-arcconf-plugin
    - libstoragemgmt-hpsa-plugin
    - libstoragemgmt-local-plugin
    - libstoragemgmt-megaraid-plugin
    - libstoragemgmt-nfs-plugin
    - libstoragemgmt-nstor-plugin
    - libstoragemgmt-smis-plugin
    - libstoragemgmt-targetd-plugin
    - libstoragemgmt-udev
    - libudisks2
    - lsscsi
    - python3-blivet
    - python3-blockdev
    - python3-libstoragemgmt
    - python3-pywbem
    - sg3_utils
    - udisks2
    - udisks2-iscsi
    - udisks2-lsm
    - udisks2-lvm2
    - udisks2-zram

    # Unsure packages
    # - mtx
    # - mt-st
    # - peripety
    #

  arch_packages:
    aarch64:
      - daxio
      - libpmem
      - libpmem-debug
      - libpmem-devel
      - libpmemblk
      - libpmemblk-debug
      - libpmemblk-devel
      - libpmemlog
      - libpmemlog-debug
      - libpmemlog-devel
      - libpmemobj
      - libpmemobj++-devel
      - libpmemobj++-doc
      - libpmemobj-debug
      - libpmemobj-devel
      - libpmempool
      - libpmempool-debug
      - libpmempool-devel
      - librpmem
      - librpmem-debug
      - librpmem-devel
      - libvmem
      - libvmem-debug
      - libvmem-devel
      - libvmmalloc
      - libvmmalloc-debug
      - libvmmalloc-devel
      - pmdk-convert
      - pmempool
      - pmreorder
      - rpmemd
    ppc64le:
      - daxio
      - libpmem
      - libpmem-debug
      - libpmem-devel
      - libpmemblk
      - libpmemblk-debug
      - libpmemblk-devel
      - libpmemlog
      - libpmemlog-debug
      - libpmemlog-devel
      - libpmemobj
      - libpmemobj++-devel
      - libpmemobj++-doc
      - libpmemobj-debug
      - libpmemobj-devel
      - libpmempool
      - libpmempool-debug
      - libpmempool-devel
      - librpmem
      - librpmem-debug
      - librpmem-devel
      - libvmem
      - libvmem-debug
      - libvmem-devel
      - libvmmalloc
      - libvmmalloc-debug
      - libvmmalloc-devel
      - pmdk-convert
      - pmempool
      - pmreorder
      - rpmemd
    x86_64:
      - daxio
      - libpmem
      - libpmem-debug
      - libpmem-devel
      - libpmemblk
      - libpmemblk-debug
      - libpmemblk-devel
      - libpmemlog
      - libpmemlog-debug
      - libpmemlog-devel
      - libpmemobj
      - libpmemobj++-devel
      - libpmemobj++-doc
      - libpmemobj-debug
      - libpmemobj-devel
      - libpmempool
      - libpmempool-debug
      - libpmempool-devel
      - librpmem
      - librpmem-debug
      - librpmem-devel
      - libvmem
      - libvmem-debug
      - libvmem-devel
      - libvmmalloc
      - libvmmalloc-debug
      - libvmmalloc-devel
      - pmdk-convert
      - pmempool
      - pmreorder
      - rpmemd

  labels:
  - eln
