document: feedback-pipeline-workload
version: 1
data:
  name: Editors
  description: Editors
  maintainer: sst_cs_plumbers

  packages:
  - emacs
  - emacs-lucid
  - emacs-nox
  - emacs-auctex
  - nano

  labels:
  - eln
  - c9s
