document: feedback-pipeline-workload
version: 1
data:
  name: GCC
  description: Collection of packages providing the C, C++, and Fortran compilers.
  maintainer: sst_pt_gcc
  packages:
    - gcc
    - gcc-c++
    - cpp
    - gcc-gfortran
    - gcc-plugin-devel
    - libasan
    - libatomic
    - libgcc
    - libgfortran
    - libgomp
    - libitm
    - libitm-devel
    - libstdc++
    - libstdc++-devel
    - libstdc++-docs
    - libstdc++-static
    - libubsan
    - libmpc
    - dwz
    - chrpath
  arch_packages:
    aarch64:
      - liblsan
      - libtsan
    i686:
      - libquadmath
      - libquadmath-devel
    ppc64le:
      - gcc-offload-nvptx
      - libgomp-offload-nvptx
      - liblsan
      - libtsan
      - libquadmath
      - libquadmath-devel
    x86_64:
      - gcc-offload-nvptx
      - libgomp-offload-nvptx
      - liblsan
      - libtsan
      - libquadmath
      - libquadmath-devel
  labels:
    - eln
    - c9s
    - c10s
