document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted PMDK packages
  description: Unwanted Persistent Memory Development Kit components
  maintainer: sst_storage_io
  unwanted_source_packages:
    - nvml
    - libpmemobj-cpp
    - pmdk-convert
  labels:
    - eln
