---
document: feedback-pipeline-workload
version: 1
data:
  name: Kdump support
  description: Tools necessary to support vmcore dumping and analyzing
  maintainer: sst_kernel_debug

  packages:
  - kexec-tools
  - kdump-anaconda-addon
  - memstrack
  - crash
  - snappy
  - crash-trace-command
  - libkdumpfile
  - drgn
    # Read ftrace data from a core dump file.

  arch_packages:
    aarch64:
      - crash-gcore-command
        # Adds a "gcore" command which can create a core dump file of a user-space task that was running in a kernel dumpfile.
    ppc64le:
      - crash-gcore-command
    x86_64:
      - crash-gcore-command

  labels:
  - eln
  - c9s
