document: feedback-pipeline-workload
version: 1
data:
  name: Brasero
  description: Default physical media burner application in Workstation
  maintainer: sst_display_desktop_foundation
  packages: []
  arch_packages:
    ppc64le:
      - brasero
      # Disabled until https://gitlab.gnome.org/GNOME/brasero/-/merge_requests/21 is merged
      # - brasero-nautilus
    x86_64:
      - brasero
      # Disabled until https://gitlab.gnome.org/GNOME/brasero/-/merge_requests/21 is merged
      # - brasero-nautilus
  labels:
    - eln
    - c10s
