document: feedback-pipeline-workload
version: 1
data:
  name: Graphics development libraries
  description: Libraries used for development of graphics applications
  maintainer: sst_display_hardware_multimedia
  packages:
    - libdecor
    - SDL
    - SDL2
    - sdl2-compat
    - SDL3
  labels:
    - eln
    - c10s
