document: feedback-pipeline-workload
version: 1
data:
  name: Other packages from SST CS Aps for ELN
  description: Unsorted tools owned by CS Apps SST
  maintainer: sst_cs_apps

  packages:
  - less
  - time
  - pcre2
  - pcre2-devel
  - quota
  - quota-nld
  - quota-rpc
  - quota-doc
  - quota-nls
  - quota-warnquota

  labels:
  - eln
