document:  feedback-pipeline-workload
version: 1
data:
    name: kernel-rt devel/debug
    description: Kernel RT packages used for devel/debug
    maintainer: sst_kernel_rats
    packages: []

    arch_packages:
      x86_64:
        - kernel-rt-debug
        - kernel-rt-debug-core
        - kernel-rt-debug-modules
        - kernel-rt-debug-modules-extra
        - kernel-rt-debug-kvm
        - kernel-rt-debuginfo-common-x86_64
        - kernel-rt-debuginfo
        - kernel-rt-devel
        - kernel-rt-debug-devel

    labels:
        - c9s
