document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted packages for PostgreSQL
  description: Packages we do not want to ship for PostgreSQL
  maintainer: sst_cs_apps

  unwanted_packages:
  - postgresql-llvmjit

  labels:
  - eln
  - c9s
