document: feedback-pipeline-workload
version: 1
data:
  name: rt-setup
  description: Package that creates realtime group and limits
  maintainer: sst_kernel_rats
  packages: []
  labels:
  - eln
  - c9s

  package_placeholders:
    rt-setup:
      srpm: rt-setup
      description: This package is not in Fedora (yet), but we want it here.
      requires:
      - pam
      - shadow-utils
      - kexec-tools
      - tuna
      - tuned
      - tuned-profiles-realtime
      - systemd
      buildrequires:
      - gcc
      - systemd
      - annobin
      limit_arches:
      - x86_64
