document: feedback-pipeline-workload
version: 1
data:
  name: Image libraries
  description: Popular libraries for image processing (JPEG, TIFF, PNG)
  maintainer: sst_cs_apps

  packages:
  - libpng-devel
  - libtiff-devel

  labels:
  - eln
