document: feedback-pipeline-workload
version: 1
data:
  name: OpenSCAP Reporting
  description: Wrappers and utilities for reporting results created by OpenSCAP.
  maintainer: sst_security_compliance

  packages:
  - openscap-report

  labels:
  - eln
