document: feedback-pipeline-workload
version: 1
data:
  name: Unsorted - CS System management SST
  description: Packages that doesn't fit other categories from CS System management SST
  maintainer: sst_cs_system_management

  packages:

  - rootfiles
  - libburn-doc
  - libisofs-doc
  - exchange-bmc-os-info
  - bmc-snmp-proxy
  - libucil
  - libucil-devel
  - libunicap-devel
  - libunicap
  - ptscotch-mpich-devel-parmetis
  - ptscotch-mpich
  - ptscotch-openmpi
  - ptscotch-openmpi-devel
  - scotch-devel
  - ptscotch-mpich-devel
  - ptscotch-openmpi-devel-parmetis
  - scotch
  - scotch-doc
  - bc
  - tracer

  labels:
  - eln
