document: feedback-pipeline-unwanted
version: 1
data:
  name: TPM Exclusion List
  description: TPM packages that are no longer needed
  maintainer: sst_kernel_rats

  unwanted_packages:
  - tpm-quote-tools

  labels:
  - eln
