document: feedback-pipeline-workload
version: 1
data:
  name: Debuggers
  description: Debuggers and components
  maintainer: sst_pt_perf_debug
  packages:
    - gdb
    - gdb-doc
    - gdb-gdbserver
    - gdb-headless
    - libbabeltrace
    - libbabeltrace-devel
    - source-highlight
    # See libipt below
  labels:
    - eln
    - c9s
    - c10s
  # libipt is Intel only
  # gdb-minimal is supported on everything but i686
  arch_packages:
    aarch64:
      - gdb-minimal
    i686:
      - libipt
      - libipt-devel
    ppc64le:
      - gdb-minimal
    s390x:
      - gdb-minimal
    x86_64:
      - libipt
      - libipt-devel
      - gdb-minimal
