document: feedback-pipeline-workload
version: 1
data:
  name: System monitoring - CS system management
  description: Packages for system monitoring from CS system management SST
  maintainer: sst_cs_system_management

  packages:
  - iotop
  - pciutils-devel
  - pciutils-devel-static
  - pciutils-libs
  - pciutils
  - smartmontools
  - libdap-devel
  - libdap
  - libdap-doc
  - watchdog
  - net-snmp-libs
  - net-snmp-utils
  - net-snmp-agent-libs
  - net-snmp-perl
  - net-snmp-devel
  - net-snmp

  labels:
  - eln
