document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted High Availability packages
  description: Unwanted High Availability Components
  maintainer: sst_high_availability

  unwanted_packages:
  - clufter-bin
  - clufter-cli
  - clufter-common
  - clufter-lib-ccs
  - clufter-lib-general
  - clufter-lib-pcs
  - jing-trang
  - python3-clufter
  - python-sphinxcontrib-apidoc
  - python-sphinxcontrib-apidoc
  - python-pyperclip
  - python-testrepository
  - python-hacking
  - python-ddt
  - python-certifi
  - python-kerberos
  - python-simplejson
  - python-mimeparse
  - zeromq
  - python-extras
  - python-monotonic
  - python-voluptuous
  - python-dulwich
  - python-colorama
  - python-oslo-sphinx
  - python-testscenarios
  - python-sphinx-epytext
  - python-cliff
  - python-cmd2
  - python-testtools
  - python-openstackdocstheme
  - python-oslotest
  - python-requests-mock
  - python-sqlalchemy
  - python-zmq
  - python-stestr
  - python-mox3
  - python-oslo-config
  - python-rfc3986
  - python-fixtures
  - openpgm
  - python-d2to1
  - future
  - python-requests-kerberos
  - python-msgpack
  - python-wrapt
  - python-os-service-types
  - esmtp
  - python-novaclient
  - libesmtp
  - python-pbr
  - python-debtcollector
  - python-oslo-serialization
  - python-keystoneauth1
  - python-stevedore
  - python-oslo-i18n
  - python-oslo-utils
  - python-funcsigs
  - python-iso8601
  - python-jwt
  - python-pexpect
  - python-ptyprocess

  labels:
  - eln
  - c9s
