document: feedback-pipeline-workload
version: 1
data:
  name: Networking Tools
  description: >
    Packages related to network configuration and troubleshooting.
  maintainer: sst_networking
  packages:
  - ethtool
  - iperf3
  - iproute
  - iproute-tc
  - iptraf-ng
  - iputils
  # ndptool, sends Unsolicited NA
  - libndp
  # LLDP support
  - lldpad
  - lldpd
  - mtr
  - nmap
  - nmap-ncat
  - plotnetcfg
  - python3-scapy
  - socat
  - tcpdump
  - traceroute
  - wireshark
  - wireshark-cli

  labels:
  - eln
