document: feedback-pipeline-workload
version: 1
data:
  name: Cheese
  description: Default application for handling webcams in Workstation
  maintainer: sst_desktop

  packages:
   - cheese

  labels:
  - eln
