document: feedback-pipeline-workload
version: 1
data:
  name: Python runtime
  description: Python interpretter and packages to create virtual environments and pip-install packages from PyPI
  maintainer: sst_cs_apps

  packages:
  - python3
  - python3-libs
  - python3-pip
  - python3-setuptools
  - python-unversioned-command

  labels:
  - eln
  - c9s
