document: feedback-pipeline-workload
version: 1
data:
  name: Math tools from CS System management SST
  description: Tools for mathematic operations from CS System management SST
  maintainer: sst_cs_system_management

  packages:

  - SuperLU-doc
  - SuperLU
  - SuperLU-devel

  labels:
  - eln
