document: feedback-pipeline-workload
version: 1
data:
  name: GIMP package from CS system management SST
  description: Packages for GIMP from CS system management SST
  maintainer: sst_cs_system_management

  packages:
  - gimp
  - gimp-libs
  - gegl04
  - mypaint-brushes

  labels:
  - c9s
