document: feedback-pipeline-workload
version: 1
data:
  name: efivar
  description: Tools to manage UEFI variables
  maintainer: sst_desktop_firmware_bootloaders
  packages: 
    - mandoc
  labels:
    - eln
    - c10s
  arch_packages:
    aarch64:
      - efivar
    x86_64:
      - efivar
