document: feedback-pipeline-workload
version: 1
data:
  name: System monitoring - CS system management
  description: Packages for system monitoring from CS system management SST
  maintainer: sst_cs_system_management

  packages:
  - iotop
  - libdap
  - libdap-devel
  - net-snmp
  - net-snmp-devel
  - net-snmp-libs
  - net-snmp-utils
  - pciutils
  - pciutils-devel
  - pciutils-libs
  - smartmontools

  arch_packages:
    ppc64le:
    - servicelog

  labels:
  - eln
  - c9s
