document: feedback-pipeline-workload
version: 1
data:
  name: Nautilus
  description: Default file manager in Workstation
  maintainer: sst_desktop_applications
  packages:
    - gvfs
    - gvfs-client
    - gvfs-fuse
    - gvfs-goa
    - gvfs-smb
    - libmtp
    - nautilus
    - wsdd
  arch_packages:
    aarch64:
      - gvfs-gphoto2
      - gvfs-mtp
    ppc64le:
      - gvfs-gphoto2
      - gvfs-mtp
    # not built on s390x
    x86_64:
      - gvfs-gphoto2
      - gvfs-mtp
  labels:
    - eln
    - c10s
