document: feedback-pipeline-workload
version: 1
data:
  name: OpenJDK
  description: OpenJDK and the Java Platform
  maintainer: sst_java
  labels:
  - eln

  packages:
  - java-17-openjdk
  - java-17-openjdk-demo
  - java-17-openjdk-devel
  - java-17-openjdk-headless
  - java-17-openjdk-javadoc
  - java-17-openjdk-javadoc-zip
  - java-17-openjdk-jmods
  - java-17-openjdk-src
  - java-17-openjdk-static-libs
  - copy-jdk-configs
  # Debug packages should be built but shipped in CRB
  - java-17-openjdk-slowdebug
  - java-17-openjdk-demo-slowdebug
  - java-17-openjdk-devel-slowdebug
  - java-17-openjdk-headless-slowdebug
  - java-17-openjdk-jmods-slowdebug
  - java-17-openjdk-src-slowdebug
  - java-17-openjdk-static-libs-slowdebug
  # Core tool for JDK support work
  - byteman
  - byteman-bmunit
  - byteman-javadoc

  # no s390x fastdebug due to build times
  arch_packages:
    aarch64:
    - java-17-openjdk-fastdebug
    - java-17-openjdk-demo-fastdebug
    - java-17-openjdk-devel-fastdebug
    - java-17-openjdk-headless-fastdebug
    - java-17-openjdk-jmods-fastdebug
    - java-17-openjdk-src-fastdebug
    - java-17-openjdk-static-libs-fastdebug
    ppc64le:
    - java-17-openjdk-fastdebug
    - java-17-openjdk-demo-fastdebug
    - java-17-openjdk-devel-fastdebug
    - java-17-openjdk-headless-fastdebug
    - java-17-openjdk-jmods-fastdebug
    - java-17-openjdk-src-fastdebug
    - java-17-openjdk-static-libs-fastdebug
    x86_64:
    - java-17-openjdk-fastdebug
    - java-17-openjdk-demo-fastdebug
    - java-17-openjdk-devel-fastdebug
    - java-17-openjdk-headless-fastdebug
    - java-17-openjdk-jmods-fastdebug
    - java-17-openjdk-src-fastdebug
    - java-17-openjdk-static-libs-fastdebug

  package_placeholders:
    java-21-openjdk:
      srpm: java-21-openjdk
      description: Future long-term supported release of OpenJDK
      requires:
        - fontconfig
        - xorg-x11-fonts-Type1
        - ca-certificates
        - javapackages-filesystem
        - tzdata-java
        - copy-jdk-configs
        - cups-libs
      buildrequires:
        - autoconf
        - automake
        - alsa-lib-devel
        - binutils
        - cups-devel
        - desktop-file-utils
        - elfutils-devel
        - file
        - fontconfig-devel
        - gcc-c++
        - gdb
        - libX11-devel
        - libXi-devel
        - libXinerama-devel
        - libXrandr-devel
        - libXrender-devel
        - libXt-devel
        - libXtst-devel
        - libxslt
        - nss-devel
        - pkgconfig
        - xorg-x11-proto-devel
        - zip
        - tar
        - unzip
        - javapackages-filesystem
        - libffi-devel
        - tzdata-java
        - ca-certificates
        - gcc
        - systemtap-sdt-devel
        - make
