document: feedback-pipeline-workload
version: 1
data:
  name: gnu-efi
  description: Development Libraries and headers for EFI
  maintainer: sst_desktop_firmware_bootloaders
  packages: []
  labels:
    - eln
    - c9s
    - c10s
  arch_packages:
    armv7hl:
      - gnu-efi
    aarch64:
      - gnu-efi
    x86_64:
      - gnu-efi
