document: feedback-pipeline-workload
version: 1
data:
  name: Networking Tools - LLDP
  description: >
    Packages related to network configuration and troubleshooting.

  maintainer: sst_network_fastdatapath
  packages:
    # LLDP support
    - lldpad
    - lldpd
  labels:
    - eln
    - c9s
