document: feedback-pipeline-workload
version: 1
data:
  name: bootc
  description: >
    OS compontents for bootc based systems for ELN.
  maintainer: sst_bootc

  packages:
  - bootc
  - composefs
  - initoverlayfs

  labels:
  - c10s
  - eln
  - c9s
