document: feedback-pipeline-workload
version: 1
data:
    name: realtime tracing programs
    description: Packages for tracing
    maintainer: sst_kernel_rats
    packages:
        - trace-cmd
        - kernelshark
    labels:
        - eln
