document: feedback-pipeline-workload
version: 1
data:
  name: Tomcat packages
  description: Middleware SST - Tomcat packages
  maintainer: sst_middleware

  packages:
  - ecj
  - tomcat
  - tomcat-admin-webapps
  - tomcat-docs-webapp
  - tomcat-el-3.0-api
  - tomcat-jsp-2.3-api
  - tomcat-lib
  - tomcat-servlet-4.0-api
  - tomcat-webapps
  - mod_proxy_cluster

  labels:
  - eln
  - c9s
  - c10s
