document: feedback-pipeline-workload
version: 1
data:
  name: dbxtool
  description: Secure Boot DBX updater
  maintainer: sst_desktop

  packages: []

  labels:
  - eln

  arch_packages:
    aarch64:
      - dbxtool
    x86_64:
      - dbxtool
