document: feedback-pipeline-workload
version: 1
data:
  name: Cronie
  description: A standard UNIX daemon crond that runs specified programs at scheduled times
  maintainer: sst_cs_apps

  packages:
  - at
  - cronie

  labels:
  - eln
