document: feedback-pipeline-workload
version: 1
data:
  name: SCM
  description: Pupular source-management tools
  maintainer: sst_cs_apps

  packages:
  - git
  - git-daemon
  - git-gui
  - gitk

  labels:
  - eln

  package_placeholders:
    git-lfs:
      srpm: git-lfs
      description: Git extension for versioning large files
      requires:
        - git-core

      buildrequires:
        - perl-Digest-SHA
        - perl-Test-Harness
        - git