document: feedback-pipeline-workload
version: 1
data:
  name: Desktop Network Management
  description: >
    The Network Management tools for the desktop environment, including
    bluetooh, WIFI, IPSec VPN, Cellular network supports.
  maintainer: sst_network_management
  packages:
  # Core
  - iproute
  - dhcp-client
  - dnsmasq
  - NetworkManager
  - NetworkManager-tui

  # Cellular Modem
  - ModemManager
  - ModemManager-glib
  - NetworkManager-ppp
  - NetworkManager-wwan
  - mobile-broadband-provider-info
  - usb_modeswitch
  - usb_modeswitch-data

  # VPN
  - NetworkManager-libreswan
  - NetworkManager-libreswan-gnome

  # Wifi
  - NetworkManager-wifi
  - wpa_supplicant

  # Bluetooh
  - NetworkManager-bluetooth
  - bluez
  - bluez-libs

  # GUI
  - network-manager-applet
  - nm-connection-editor

  labels:
  - eln
  - c9s
