document: feedback-pipeline-workload
version: 1
data:
  name: Python psutil
  description: A process and system utilities module for Python, included because it's useful both for customers and internal needs, if similar functionality ever gets into the Python standard library, we will reconsider this workload
  maintainer: sst_cs_apps
  packages:
    - python3-psutil
  labels:
    - eln
    - c10s
