document: feedback-pipeline-workload
version: 1
data:
  name: System tracing
  description: A collection of common system tracing tools
  maintainer: sst_kernel_tps

  packages:
  - bcc
  - strace
  - trace-cmd
  - libtracefs
  - libtraceevent
  - kernelshark

  arch_packages:
    aarch64:
      - bpftrace
      - opencsd
      - opencsd-devel
    ppc64le:
      - bpftrace
    s390x:
      - bpftrace
    x86_64:
      - bpftrace

  labels:
  - eln
  - c9s
