document: feedback-pipeline-workload
version: 1
data:
  name: Text processing packages from CS system management SST
  description: Packages for text processing/generating documentation from CS system management SST
  maintainer: sst_cs_system_management

  packages:
  - docbook-dtds
  - docbook-style-dsssl
  - docbook-style-xsl
  - docbook-utils-pdf
  - docbook-utils
  - docbook5-schemas
  - docbook5-style-xsl
  - docbook5-style-xsl-extensions
  - help2man
  - linuxdoc-tools
  - openjade
  - opensp
  - opensp-devel
  - perl-SGMLSpm
  - sgml-common
  - xml-common
  - xmlto
  - xmlto-xhtml
  - xmlto-tex
  - xmltoman
  - texinfo-tex
  - texinfo
  - doxygen
  - doxygen-latex
  - doxygen-doxywizard
  - latex2html
  - latexmk
  - passivetex
  - perl-Unicode-EastAsianWidth
  - tex-fonts-hebrew
  - texi2html
  - texlive-tex
  - texlive-xetex
  - texlive-dvipng
  - texlive-metapost
  - texlive
  - texlive-makeindex
  - texlive-lib-devel
  - texlive-dvipdfmx
  - texlive-xdvi
  - texlive-pdftex
  - texlive-lib
  - texlive-bibtex
  - texlive-mfware
  - texlive-metafont
  - texlive-kpathsea
  - texlive-tex4ht
  - texlive-fontware
  - texlive-dvisvgm
  - texlive-dvips
  - texlive-gsftopk
  - texlive-luatex
  - texlive-datetime
  - texlive-symbol
  - texlive-texlive-docindex
  - texlive-ctablestack
  - texlive-anyfontsize
  - texlive-xmltexconfig
  - texlive-wrapfig
  - texlive-sauerj
  - texlive-scheme-basic
  - texlive-carlisle
  - texlive-eqparbox
  - texlive-xeindex
  - texlive-bidi
  - texlive-changebar
  - texlive-etex-pkg
  - texlive-linegoal
  - texlive-mdwtools
  - texlive-multirow
  - texlive-lualibs
  - texlive-garuda-c90
  - texlive-collection-htmlxml
  - texlive-ifoddpage
  - texlive-tabulary
  - texlive-tex-gyre
  - texlive-tools
  - texlive-xetexfontinfo
  - texlive-collection-latex
  - texlive-setspace
  - texlive-enctex
  - texlive-environ
  - texlive-mparhack
  - texlive-pst-math
  - texlive-wasy
  - texlive-classpack
  - texlive-fancyvrb
  - texlive-typehtml
  - texlive-ms
  - texlive-marginnote
  - texlive-eso-pic
  - texlive-listings
  - texlive-import
  - texlive-multido
  - texlive-lm
  - texlive-xepersian
  - texlive-chngcntr
  - texlive-collection-xetex
  - texlive-pxfonts
  - texlive-base
  - texlive-float
  - texlive-lua-alt-getopt
  - texlive-eepic
  - texlive-pst-3d
  - texlive-helvetic
  - texlive-filehook
  - texlive-sectsty
  - texlive-xcolor
  - texlive-pslatex
  - texlive-fontbook
  - texlive-fontwrap
  - texlive-pst-grad
  - texlive-stmaryrd
  - texlive-soul
  - texlive-euler
  - texlive-jknapltx
  - texlive-bibtopic
  - texlive-cm
  - texlive-charter
  - texlive-threeparttable
  - texlive-csquotes
  - texlive-seminar
  - texlive-tocloft
  - texlive-cmextra
  - texlive-ulem
  - texlive-latex
  - texlive-ucs
  - texlive-cns
  - texlive-finstrut
  - texlive-xecjk
  - texlive-breakurl
  - texlive-xetex-pstricks
  - texlive-babelbib
  - texlive-lualatex-math
  - texlive-pst-plot
  - texlive-ntgclass
  - texlive-ncntrsbk
  - texlive-filecontents
  - texlive-pst-coil
  - texlive-epsf
  - texlive-titlesec
  - texlive-adjustbox
  - texlive-upquote
  - texlive-lm-math
  - texlive-courier
  - texlive-luatexbase
  - texlive-xmltex
  - texlive-glyphlist
  - texlive-appendix
  - texlive-bookman
  - texlive-fmtcount
  - texlive-fancybox
  - texlive-pstricks-add
  - texlive-l3packages
  - texlive-latexconfig
  - texlive-ucharclasses
  - texlive-plain
  - texlive-xecyr
  - texlive-tetex
  - texlive-fix2col
  - texlive-arabxetex
  - texlive-overpic
  - texlive-url
  - texlive-fncychap
  - texlive-wadalab
  - texlive-xstring
  - texlive-epstopdf
  - texlive-footmisc
  - texlive-pstricks
  - texlive-etex
  - texlive-fonts-tlwg
  - texlive-euro
  - texlive-realscripts
  - texlive-utopia
  - texlive-babel-english
  - texlive-wasy2-ps
  - texlive-memoir
  - texlive-babel
  - texlive-etoolbox
  - texlive-attachfile
  - texlive-graphics-def
  - texlive-oberdiek
  - texlive-placeins
  - texlive-marvosym
  - texlive-anysize
  - texlive-fontawesome
  - texlive-index
  - texlive-cmap
  - texlive-subfig
  - texlive-geometry
  - texlive-thumbpdf
  - texlive-psfrag
  - texlive-avantgar
  - texlive-ncctools
  - texlive-koma-script
  - texlive-xesearch
  - texlive-xetex-itrans
  - texlive-algorithms
  - texlive-bera
  - texlive-luatex85
  - texlive-ec
  - texlive-capt-of
  - texlive-pst-arrow
  - texlive-svn-prov
  - texlive-ifxetex
  - texlive-zapfding
  - texlive-times
  - texlive-luaotfload
  - texlive-metalogo
  - texlive-cm-super
  - texlive-framed
  - texlive-cite
  - texlive-xltxtra
  - texlive-mnsymbol
  - texlive-pspicture
  - texlive-wasysym
  - texlive-pst-tree
  - texlive-pst-eps
  - texlive-unisugar
  - texlive-philokalia
  - texlive-type1cm
  - texlive-kastrup
  - texlive-collection-basic
  - texlive-xkeyval
  - texlive-ae
  - texlive-palatino
  - texlive-amsfonts
  - texlive-xtab
  - texlive-section
  - texlive-hyph-utf8
  - texlive-needspace
  - texlive-latex-fonts
  - texlive-ltabptch
  - texlive-passivetex
  - texlive-pdfpages
  - texlive-caption
  - texlive-rsfs
  - texlive-mathpazo
  - texlive-cm-lgc
  - texlive-parskip
  - texlive-beton
  - texlive-paralist
  - texlive-xetex-tibetan
  - texlive-subfigure
  - texlive-lineno
  - texlive-fancyref
  - texlive-tex-ini-files
  - texlive-mflogo-font
  - texlive-crop
  - texlive-updmap-map
  - texlive-jadetex
  - texlive-collection-fontsrecommended
  - texlive-graphics-cfg
  - texlive-lettrine
  - texlive-kerkis
  - texlive-colortbl
  - texlive-latex2man
  - texlive-zapfchan
  - texlive-fpl
  - texlive-txfonts
  - texlive-cjk
  - texlive-texlive.infra
  - texlive-tex-gyre-math
  - texlive-texlive-common-doc
  - texlive-microtype
  - texlive-mfnfss
  - texlive-booktabs
  - texlive-breqn
  - texlive-fp
  - texlive-pst-tools
  - texlive-knuth-lib
  - texlive-fontspec
  - texlive-xecolor
  - texlive-textcase
  - texlive-hyphenat
  - texlive-mathspec
  - texlive-ctable
  - texlive-graphics
  - texlive-pst-blur
  - texlive-powerdot
  - texlive-manfnt-font
  - texlive-textpos
  - texlive-texlive-scripts
  - texlive-euenc
  - texlive-ifluatex
  - texlive-underscore
  - texlive-psnfss
  - texlive-amsmath
  - texlive-mathtools
  - texlive-pgf
  - texlive-pst-slpe
  - texlive-makecmds
  - texlive-amscls
  - texlive-fancyhdr
  - texlive-polyglossia
  - texlive-ifmtarg
  - texlive-showexpl
  - texlive-knuth-local
  - texlive-was
  - texlive-preprint
  - texlive-l3kernel
  - texlive-mptopdf
  - texlive-titling
  - texlive-sepnum
  - texlive-texlive-msg-translations
  - texlive-collection-latexrecommended
  - texlive-bigfoot
  - texlive-changepage
  - texlive-lastpage
  - texlive-uhc
  - texlive-pst-node
  - texlive-trimspaces
  - texlive-extsizes
  - texlive-hyphen-base
  - texlive-varwidth
  - texlive-enumitem
  - texlive-texlive-en
  - texlive-iftex
  - texlive-natbib
  - texlive-unicode-data
  - texlive-l3experimental
  - texlive-ptext
  - texlive-currfile
  - texlive-hyperref
  - texlive-xifthen
  - texlive-awesomebox
  - texlive-pst-text
  - texlive-eurosym
  - texlive-arphic
  - texlive-beamer
  - texlive-mflogo
  - texlive-fixlatvian
  - texlive-ltxmisc
  - texlive-qstest
  - texlive-texconfig
  - texlive-parallel
  - texlive-t2
  - texlive-rcs
  - texlive-xetexconfig
  - texlive-ifetex
  - texlive-collectbox
  - texlive-pst-fill
  - texlive-unicode-math
  - texlive-tabu
  - texlive-xunicode
  - texlive-tipa
  - texlive-norasi-c90
  - texlive-sansmath
  - asciidoc-doc
  - asciidoc-latex
  - asciidoc
  - librx
  - librx-devel

  labels:
  - eln
