document: feedback-pipeline-unwanted
version: 1
data:
  name: Progam level unwanted packages
  description: Unwanted packages
  maintainer: jwboyer

  unwanted_packages:
    - bodhi-client
    - bodhi-composer
    - bodhi-docs
    - bodhi-server
    - cmake-fedora
    - python3-bodhi
    - python3-bodhi-client
    - python3-bodhi-messages
    - btrfs-progs
    - btrfs-progs-devel
    - erlang
    - etcd
    - compat-golang-github-coreos-etcd-devel
    - golang-etcd-devel
    - golang-etcd-etcdserver-api-3rpc-devel
    - fedora-packager
    - fedora-packager-yubikey
    - fedpkg
    - fedpkg-stage
    - ghc
    - ImageMagick
    - ImageMagick-c++
    - ImageMagick-c++-devel
    - ImageMagick-devel
    - ImageMagick-libs
    - ImageMagick-perl
    - imake
    - koji
    - koji-builder
    - koji-builder-plugins
    - koji-hub
    - koji-utils
    - koji-vm
    - koji-web
    - python3-koji
    - python3-koji-cli-plugins
    - python3-koji-hub
    - python3-koji-hub-plugins
    - python3-koji-web
    - mono-core
    - mono-data
    - mono-data-sqlite
    - mono-devel
    - mono-extras
    - mono-mvc
    - mono-wcf
    - mono-web
    - mono-winforms
    - monodoc
    - monodoc-devel
    - nagios-plugins
    - nagios-plugins-all
    - nagios-plugins-apt
    - nagios-plugins-breeze
    - nagios-plugins-by_ssh
    - nagios-plugins-cluster
    - nagios-plugins-dbi
    - nagios-plugins-dhcp
    - nagios-plugins-dig
    - nagios-plugins-disk
    - nagios-plugins-disk_smb
    - nagios-plugins-dns
    - nagios-plugins-dummy
    - nagios-plugins-file_age
    - nagios-plugins-flexlm
    - nagios-plugins-fping
    - nagios-plugins-game
    - nagios-plugins-hpjd
    - nagios-plugins-http
    - nagios-plugins-icmp
    - nagios-plugins-ide_smart
    - nagios-plugins-ifoperstatus
    - nagios-plugins-ifstatus
    - nagios-plugins-ircd
    - nagios-plugins-ldap
    - nagios-plugins-load
    - nagios-plugins-log
    - nagios-plugins-mailq
    - nagios-plugins-mrtg
    - nagios-plugins-mrtgtraf
    - nagios-plugins-mysql
    - nagios-plugins-nagios
    - nagios-plugins-nt
    - nagios-plugins-ntp
    - nagios-plugins-ntp-perl
    - nagios-plugins-nwstat
    - nagios-plugins-oracle
    - nagios-plugins-overcr
    - nagios-plugins-perl
    - nagios-plugins-pgsql
    - nagios-plugins-ping
    - nagios-plugins-procs
    - nagios-plugins-radius
    - nagios-plugins-real
    - nagios-plugins-remove_perfdata
    - nagios-plugins-rpc
    - nagios-plugins-sensors
    - nagios-plugins-smtp
    - nagios-plugins-snmp
    - nagios-plugins-ssh
    - nagios-plugins-ssl_validity
    - nagios-plugins-swap
    - nagios-plugins-tcp
    - nagios-plugins-time
    - nagios-plugins-ups
    - nagios-plugins-uptime
    - nagios-plugins-users
    - nagios-plugins-wave
    - R-core
    - R-core-devel
    - R-devel
    - R-java-devel
    - R-rpm-macros
    - redhat-lsb-core
    - redhat-lsb-submod-security
    - reiserfs-utils
    - screen

  labels:
  - eln
  - c9s

