document: feedback-pipeline-unwanted
version: 1
data:
  name: Core Services Infrastructure Services - Blocked packages
  description: Core Services Infrastructure Services - Packages which should not be in ELN
  maintainer: sst_cs_infra_services

  unwanted_packages:
  # a2ps
  - a2ps
  # authd
  - authd
  # bind
  - bind-export-libs
  - bind-sdb
  - bind-sdb-chroot
  # compat-guile18
  - compat-guile18-devel
  - compat-guile18
  # dnssec-trigger
  - dnssec-trigger
  - dnssec-trigger-panel
  # espeak
  - espeak-devel
  - espeak
  # frr
  - frr-contrib
  - frr-devel
  # GeoIP
  - GeoIP
  - GeoIP-data
  - GeoIP-devel
  # geoipupdate
  - geoipupdate
  # gsm
  - gsm-tools
  # gutenprint
  - gutenprint-extras
  - gutenprint-plugin
  # hplip
  - hplip-gui
  # libidn
  - libidn
  - libidn-devel
  # libwvstreams
  - libwvstreams-devel
  - libwvstreams
  - libwvstreams-static
  # mailman
  - mailman
  # memcached
  - memcached-devel
  # ncurses
  - ncurses-compat-libs
  - ncurses-static
  # ppp
  - network-scripts-ppp
  # ntp
  - ntp
  - ntpdate
  - sntp
  - ntp-doc
  - ntp-perl
  # perl-PerlIO-gzip
  - perl-PerlIO-gzip
  # pptp
  - pptp-setup
  # python-pyudev
  - python3-pyudev-qt5
  # quagga
  - quagga
  - quagga-contrib
  - quagga-devel
  # rsh
  - rsh
  - rsh-server
  # sane-frontends
  - sane-frontends
  # slang
  - slang-slsh
  # speex
  - speex-tools
  # system-config-printer
  - system-config-printer
  - system-config-printer-applet
  # timedatex
  - timedatex
  # tuned
  - tuned-profiles-compat
  - tuned-profiles-nfv-host-bin
  - tuned-utils-systemtap
  # urw-base35-fonts
  - urw-base35-fonts-legacy
  # xsane
  - xsane-gimp
  # subversion
  - subversion-kde
  # exim
  - exim
  # pakchois
  - pakchois
  # replaced by xdebug3
  - php-pecl-xdebug

  labels:
  - eln
  - c9s
