document: feedback-pipeline-workload
version: 1
data:
  name: RDMA Stack Core Packages
  description: RDMA Stack Packages should be in ELN BaseOS repository
  maintainer: sst_network_drivers

  packages:
  - libfabric

  labels:
  - eln
  - c9s

  arch_packages:
    # not armv7hl
    aarch64:
      - libibverbs
      - libibverbs-utils
      - librdmacm
      - librdmacm-utils
      - rdma-core
      - ibacm
      - infiniband-diags
      - iwpmd
      - libibumad
      - srp_daemon
      - rdma-core-devel
      - python3-pyverbs
      - opensm
      - opensm-libs
      - perftest
    ppc64le:
      - libibverbs
      - libibverbs-utils
      - librdmacm
      - librdmacm-utils
      - rdma-core
      - ibacm
      - infiniband-diags
      - iwpmd
      - libibumad
      - srp_daemon
      - rdma-core-devel
      - python3-pyverbs
      - opensm
      - opensm-libs
      - perftest
    s390x:
      - libibverbs
      - libibverbs-utils
      - librdmacm
      - librdmacm-utils
      - rdma-core
      - ibacm
      - infiniband-diags
      - iwpmd
      - libibumad
      - srp_daemon
      - rdma-core-devel
      - python3-pyverbs
      - opensm
      - opensm-libs
      - perftest
    x86_64:
      - libibverbs
      - libibverbs-utils
      - librdmacm
      - librdmacm-utils
      - rdma-core
      - ibacm
      - infiniband-diags
      - iwpmd
      - libibumad
      - srp_daemon
      - rdma-core-devel
      - python3-pyverbs
      - opensm
      - opensm-libs
      - perftest
