document: feedback-pipeline-workload
version: 1
data:
  name: Core Network Management
  description: >
    The Core Network Management tools for the local host. This includes
    NetworkManager and related tools.
  maintainer: sst_networking
  packages:
  - dhclient
  - dnsmasq
  - iproute
  - NetworkManager
  - NetworkManager-tui

  labels:
  - eln
