document: feedback-pipeline-workload
version: 1
data:
  name: Python devel (CRB)
  description: Python development packages, distributed in the CRB
  maintainer: sst_cs_apps

  packages:
  - python3-devel
  - python3-debug
  - python3-test
  - python3-idle
  - python3-rpm-generators
  - python3-rpm-macros
  - python-srpm-macros
  - python-rpm-macros
  - pyproject-rpm-macros
  - python3-Cython
  - python3-sphinx
  - python3-wheel
  # note: the following package is called python3-wheel-wheel in RHEL proper:
  - python-wheel-wheel
  - python3-pytest
  - python3-psutil-tests
  - py3c-devel
  - py3c-doc

  labels:
  - eln
