document: feedback-pipeline-workload
version: 1
data:
  name: thermald
  description: Thermal Management daemon
  maintainer: sst_desktop_platform_technologies
  packages: []
  labels:
    - eln
    - c9s
  arch_packages:
    x86_64:
      - thermald
