document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Screenshot
  description: Application for taking screenshots in Workstation
  maintainer: sst_desktop

  packages:
  - gnome-screenshot

  labels:
  - c9s
