document: feedback-pipeline-workload
version: 1
data:
  name: Networking Tools - traceroute
  description: >
    Packages related to network configuration and troubleshooting.
  maintainer: sst_networking_core
  packages:
  - traceroute

  labels:
  - eln
  - c9s
