document: feedback-pipeline-workload
version: 1
data:
  name: System management - CS system management
  description: Packages for managing Linux system from CS system management SST
  maintainer: sst_cs_system_management

  packages:

  - libwsman-devel
  - libwsman1
  - openwsman-server
  - sblim-cmpi-base
  - sblim-cmpi-base-devel
  - libcmpiCppImpl0
  - sblim-cmpi-devel
  - sblim-indication_helper
  - sblim-indication_helper-devel
  - sblim-sfcb
  - sblim-sfcc
  - sblim-sfcc-devel
  - sblim-wbemcli
  - tog-pegasus-devel
  - tog-pegasus-libs
  - tog-pegasus
  - wsmancli
  - Xaw3d
  - Xaw3d-devel
  - gpm-devel
  - gpm
  - gpm-libs
  - libva
  - libva-devel
  - libyami
  - python3-opencv
  - opencv-devel
  - opencv-contrib
  - opencv
  - opencv-core
  - opencv-doc
  - passwd
  - tmpwatch
  - usermode
  - usermode-gtk
  - python3-volume_key
  - volume_key
  - volume_key-libs
  - volume_key-devel
  - diffstat
  - diffutils
  - dos2unix
  - genwqe-vpd
  - genwqe-zlib
  - genwqe-zlib-static
  - genwqe-zlib-devel
  - genwqe-tools
  - iprutils
  - liboggz-doc
  - liboggz-devel
  - liboggz
  - librabbitmq-devel
  - librabbitmq
  - librabbitmq-tools
  - opal-firmware
  - opencryptoki-devel
  - opencryptoki-icsftok
  - opencryptoki-swtok
  - opencryptoki
  - opencryptoki-libs
  - opencryptoki-tpmtok
  - openhpi-libs
  - openhpi
  - openhpi-devel
  - patch
  - patchutils
  - rhel-system-roles-sap
  - setserial
  - symlinks
  - teckit
  - teckit-devel
  - which
  - libsndfile
  - libsndfile-devel
  - libsndfile-utils
  - mksh
  - uuid-c++
  - uuid-devel
  - uuid-perl
  - uuid-dce
  - uuid-c++-devel
  - uuid
  - uuid-dce-devel
  - OpenIPMI-devel
  - OpenIPMI-perl
  - python3-openipmi
  - OpenIPMI-libs
  - OpenIPMI-lanserv
  - OpenIPMI
  - freeipmi
  - freeipmi-ipmidetectd
  - freeipmi-bmc-watchdog
  - freeipmi-devel
  - freeipmi-ipmiseld
  - ipmitool
  - ipmievd
  - babl
  - babl-devel
  - babl-devel-docs
  - dcraw
  - gegl04
  - gegl04-devel
  - gegl04-devel-docs
  - gegl04-tools
  - jasper
  - jasper-libs
  - jasper-devel
  - jasper-utils
  - libgphoto2-devel
  - libgphoto2
  - netpbm-doc
  - netpbm-progs
  - netpbm
  - netpbm-devel
  - python3-jmespath

  labels:
  - eln
