document: feedback-pipeline-workload
version: 1
data:
  name: RHEL Lightspeed
  description: Command Line Assistant powered by RHEL Lightspeed.
  maintainer: sst_rhel_lightspeed
  packages: []
  package_placeholders:
    - srpm_name: command-line-assistant
      limit_arches:
        - aarch64
        - x86_64
      rpms:
        - rpm_name: command-line-assistant
          description: Command Line Assistant
          dependencies:
            - python3
            - python3-dasbus
            - python3-requests
            - python3-sqlalchemy
            - systemd
        - rpm_name: command-line-assistant-selinux
          description: Command Line Assistant SELinux Policy
          dependencies:
            - selinux-policy-targeted
  labels:
    - eln
    - c10s
