document: feedback-pipeline-workload
version: 1
data:
  name: binutils/annobin
  description: Set of packages that GCC depends on
  maintainer: sst_pt_gcc

  packages:
  - binutils
  - binutils-devel
  - binutils-gold
  - annobin-annocheck
  - annobin-plugin-gcc

  labels:
  - eln
