document: feedback-pipeline-workload
version: 1
data:
  name: RDMA Stack Appstream Packages
  description: RDMA Stack - Packages should be in ELN
  maintainer: sst_network_drivers
  packages:
    - libfabric-devel
    - openmpi
    - openmpi-devel
    - openmpi-java
    - openmpi-java-devel
    - python3-openmpi
    - mpich
    - mpich-autoload
    - mpich-devel
    - mpich-doc
    - python3-mpich
  labels:
    - eln
    - c9s
    - c10s
  arch_packages:
    # not armv7hl
    aarch64:
      - opensm-devel
    ppc64le:
      - opensm-devel
    s390x:
      - opensm-devel
    x86_64:
      - opensm-devel
