document: feedback-pipeline-workload
version: 1
data:
  name: FreeIPA Server - Domain Controller
  description: FreeIPA Server - Domain Controller
  maintainer: sst_identity_management

  packages:
  - freeipa-server
  - freeipa-server-trust-ad
  - freeipa-healthcheck

  labels:
  - eln
