document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted packages for Perl
  description: Packages we do not want to ship for Perl
  maintainer: sst_cs_stacks

  unwanted_packages:
  - cvs
  - mod_perl
  - perl-Algorithm-C3
  - perl-Any-Moose
  - perl-Business-ISBN
  - perl-Coro
  - perl-Crypt-Blowfish
  - perl-Crypt-Blowfish_PP
  - perl-Crypt-RC4
  - perl-DBIx-Class
  - perl-Mojolicious
  - perl-Moose
  - perl-Mouse
  - perl-PAR-Dist
  - perl-PDF-API2
  - perl-Pegex
  - perl-Perl-Critic
  - perl-PHP-Serialization
  - perl-POE
  - perl-pod2pdf
  - perl-PPI
  - perl-Sereal
  - perl-Sereal-Decoder
  - perl-Sereal-Encoder
  - perl-Spiffy
  - perl-SQL-Statement
  - perl-Syntax-Keyword-Junction
  - perl-Template-Toolkit
  - perl-Test-Apocalypse
  - perl-Test-Perl-Critic
  - perl-Text-CSV
  - perl-Text-CSV_XS
  - perl-Tk-Pod

  labels:
  - eln
