document: feedback-pipeline-workload
version: 1
data:
  name: DHCP Server
  description: DHCP Server software
  maintainer: sst_cs_infra_services

  packages:
  - dhcp-relay
  - dhcp-server

  labels:
  - c9s
