document: feedback-pipeline-workload
version: 1
data:
  name: kernel-rt base
  description: Base set of kernel-rt packages and tools to ship
  maintainer: sst_kernel_rts
  packages: []
  arch_packages:
    x86_64:
      - kernel-rt
      - kernel-rt-core
      - kernel-rt-modules
      - kernel-rt-modules-core
      - kernel-rt-modules-extra
      - kernel-rt-kvm
      - tuned-profiles-realtime
      - tuned-profiles-nfv
      - tuned-profiles-nfv-guest
      - tuned-profiles-nfv-host
  labels:
    - c9s
