document: feedback-pipeline-workload
version: 1
data:
  name: efi-srpm-macros
  description: Common RPM Macros for building EFI-related packages
  maintainer: sst_desktop

  packages:
  - efi-srpm-macros

  labels:
  - eln
  - c9s
