document: feedback-pipeline-workload
version: 1
data:
  name: CLI tools
  description: Various cli tools that makes administrator life easier
  maintainer: sst_cs_plumbers
  packages:
    - pinfo
    - usbutils
    - mlocate
    - mtr
    - mtr-gtk
    - environment-modules
    - gperf
    - iputils
    - iputils-ninfod
    - traceroute
    - lsof
    - ps_mem
    - psacct
    - psmisc
    - attr
    - file
    - findutils
    - lynx
    - tree
    - units
    - hardlink
    - uuidd
    - words
  labels:
    - c9s
