document: feedback-pipeline-workload
version: 1
data:
  name: Anaconda
  description: Graphical system installer
  maintainer: sst_installer
  labels:
    - eln
    - c10s
  packages:
    - anaconda
    - anaconda-install-img-deps
