document: feedback-pipeline-workload
version: 1
data:
  name: Printing Stack
  description: Suite of software needed for priting on Linux
  maintainer: sst_cs_infra_services

  packages:
  # tools
  - cups
  - cups-client
  - cups-filters
  - cups-ipptool
  - cups-lpd
  - foomatic
  - foomatic-db
  - ghostscript
  - ghostscript-x11
  - gutenprint
  - gutenprint-doc
  - python3-cups
  - system-config-printer-udev
  # drivers, hw enablement
  - c2esp
  - foomatic-db-ppds
  - gutenprint-cups
  - hplip
  - splix
  - pnm2ppa
  # fonts
  - urw-base35-fonts


  labels:
  - eln
