document: feedback-pipeline-workload
version: 1
data:
  name: Qt 6 Toolkit
  description: Software toolkit for developing applications
  maintainer: sst_desktop_applications

  packages:
  - python3-pyqt6
  - python3-pyqt6-base
  - python3-pyqt6-sip
  - qt6-assistant
  - qt6-designer
  - qt6-doctools
  - qt6-linguist
  - qt6-qdbusviewer
  - qt6-qt3d
  - qt6-qt3d-devel
  - qt6-qt5compat
  - qt6-qt5compat-devel
  - qt6-qtbase
  - qt6-qtbase-common
  - qt6-qtbase-devel
  - qt6-qtbase-gui
  - qt6-qtbase-mysql
  - qt6-qtbase-odbc
  - qt6-qtbase-postgresql
  - qt6-qtbase-private-devel
  - qt6-qtbase-static
  - qt6-qtcharts
  - qt6-qtcharts-devel
  - qt6-qtconnectivity
  - qt6-qtconnectivity-devel
  - qt6-qtdatavis3d
  - qt6-qtdatavis3d-devel
  - qt6-qtdeclarative
  - qt6-qtdeclarative-devel
  - qt6-qtdeclarative-static
  - qt6-qtimageformats
  - qt6-qtlanguageserver
  - qt6-qtlanguageserver-devel
  - qt6-qtlocation
  - qt6-qtlocation-devel
  - qt6-qtlottie
  - qt6-qtlottie-devel
  - qt6-qtmultimedia
  - qt6-qtmultimedia-devel
  - qt6-qtnetworkauth
  - qt6-qtnetworkauth-devel
  - qt6-qtpositioning
  - qt6-qtpositioning-devel
  - qt6-qtquick3d
  - qt6-qtquick3d-devel
  - qt6-qtquicktimeline
  - qt6-qtquicktimeline-devel
  - qt6-qtremoteobjects
  - qt6-qtremoteobjects-devel
  - qt6-qtscxml
  - qt6-qtscxml-devel
  - qt6-qtsensors
  - qt6-qtsensors-devel
  - qt6-qtserialbus
  - qt6-qtserialbus-devel
  - qt6-qtserialport
  - qt6-qtserialport-devel
  - qt6-qtshadertools
  - qt6-qtshadertools-devel
  - qt6-qtspeech
  - qt6-qtspeech-devel
  - qt6-qtspeech-speechd
  - qt6-qtsvg
  - qt6-qtsvg-devel
  - qt6-qttools
  - qt6-qttools-common
  - qt6-qttools-devel
  - qt6-qttools-libs-designer
  - qt6-qttools-libs-designercomponents
  - qt6-qttools-libs-help
  - qt6-qttools-static
  - qt6-qttranslations
  - qt6-qtvirtualkeyboard
  - qt6-qtvirtualkeyboard-devel
  - qt6-qtwayland
  - qt6-qtwayland-devel
  - qt6-qtwebchannel
  - qt6-qtwebchannel-devel
  - qt6-qtwebsockets
  - qt6-qtwebsockets-devel
  - qt6-rpm-macros
  - qt6-srpm-macros
  # GNOME integration
  - qadwaitadecorations-qt6
  labels:
  - eln
