document: feedback-pipeline-workload
version: 1
data:
  name: Configuration Compliance content
  description: Set of Configuration Compliance recommendations in SCAP, Ansible and other formats.
  maintainer: sst_security_compliance

  packages:
  - scap-security-guide
  - scap-security-guide-doc

  labels:
  - eln
  - c9s
