document: feedback-pipeline-workload
version: 1
data:
  name: Networking Tools - wireshark
  description: >
    Packages related to network configuration and troubleshooting.
  maintainer: sst_networking_core
  packages:
  - wireshark
  - wireshark-cli

  labels:
  - eln
  - c9s
