document: feedback-pipeline-workload
version: 1
data:
  name: Nautilus
  description: Default file manager in Workstation
  maintainer: sst_desktop

  packages:
  - gvfs
  - gvfs-client
  - gvfs-fuse
  - gvfs-goa
  - gvfs-gphoto2
  - gvfs-mtp
  - gvfs-smb
  - libmtp
  - nautilus
  - sushi

  labels:
  - eln
  - c9s
