document: feedback-pipeline-workload
version: 1
data:
  name: Connections
  description: Application for managing remote connections in Workstation
  maintainer: sst_desktop_applications

  packages:
  - gnome-connections

  labels:
  - eln
  - c9s
