document: feedback-pipeline-workload
version: 1
data:
  name: Toolchain compatibility packages
  description: >
    Collection of packages providing compatibility packages related to
    the GNU Toolchain.
  maintainer: sst_platform_tools
  
  packages: []

  package_placeholders:
    # RHEL 8 bumped SONAME of libgfortran.so.  Support RHEL 7 apps.
    compat-libgfortran-48:
      description: RHEL-only compat package.
      srpm: compat-libgfortran-48
      requires:
        - binutils
        - glibc
        - glibc-devel
      buildrequires:
        - binutils
        - glibc
        - glibc-static
        - glibc-devel
        - zlib-devel
        - gettext
        - dejagnu
        - bison
        - flex
        - sharutils
        - gmp-devel
        - mpfr-devel
        - libmpc-devel
        - gdb
        - elfutils-devel
        - elfutils-libelf-devel

  labels:
  - eln
  - c9s
