document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted Packages for ELN - sst_kernel_debug
  description: Packages not shipping in ELN
  maintainer: sst_kernel_debug
  unwanted_packages:
    - netdump-server
    - crash-ptdump-command
    - python-dmidecode
    - google-benchmark
  labels:
    - eln
    - c10s
