document: feedback-pipeline-workload
version: 1
data:
  name: .NET
  description: .NET and .NET Core SDK, tools and runtime
  maintainer: sst_dotnet

  packages: []
  
  arch_packages:
    aarch64:
    - dotnet-sdk-6.0
    - dotnet-runtime-6.0
    - aspnetcore-runtime-6.0
    s390x:
    - dotnet-sdk-6.0
    - dotnet-runtime-6.0
    - aspnetcore-runtime-6.0
    x86_64:
    - dotnet-sdk-6.0
    - dotnet-runtime-6.0
    - aspnetcore-runtime-6.0

  labels:
  - eln
  - c9s
