document: feedback-pipeline-workload
version: 1
data:
  name: Hunspell Dictionaries
  description: A set of hunspell dictionaries
  maintainer: sst_i18n
  labels:
  - eln
  - c9s

  packages:
  - hunspell-af
  - hunspell-ak
  - hunspell-am
  - hunspell-as
  - hunspell-ast
  - hunspell-az
  - hunspell-be
  - hunspell-ber
  - hunspell-bg
  - hunspell-bn
  - hunspell-br
  - hunspell-ca
  - hunspell-cop
  - hunspell-csb
  - hunspell-cv
  - hunspell-cy
  - hunspell-da
  - hunspell-de
  - hunspell-dsb
  - hunspell-el
  - hunspell-en
  - hunspell-eo
  - hunspell-es
  - hunspell-et
  - hunspell-eu
  - hunspell-fa
  - hunspell-fj
  - hunspell-fo
  - hunspell-fr
  - hunspell-fur
  - hunspell-fy
  - hunspell-ga
  - hunspell-gd
  - hunspell-gl
  - hunspell-grc
  - hunspell-gu
  - hunspell-gv
  - hunspell-haw
  - hunspell-he
  - hunspell-hi
  - hunspell-hil
  - hunspell-hr
  - hunspell-hsb
  - hunspell-ht
  - hunspell-hu
  - hunspell-hy
  - hunspell-ia
  - hunspell-id
  - hunspell-is
  - hunspell-it
  - hunspell-kk
  - hunspell-km
  - hunspell-kn
  - hunspell-ko
  - hunspell-ku
  - hunspell-ky
  - hunspell-la
  - hunspell-lb
  - hunspell-ln
  - hunspell-lt
  - hunspell-lv
  - hunspell-mai
  - hunspell-mg
  - hunspell-mi
  - hunspell-mk
  - hunspell-ml
  - hunspell-mn
  - hunspell-mos
  - hunspell-mr
  - hunspell-ms
  - hunspell-mt
  - hunspell-nds
  - hunspell-ne
  - hunspell-nl
  - hunspell-nn
  - hunspell-nr
  - hunspell-nso
  - hunspell-ny
  - hunspell-oc
  - hunspell-om
  - hunspell-or
  - hunspell-pa
  - hunspell-pl
  - hunspell-pt
  - hunspell-qu
  - hunspell-quh
  - hunspell-ro
  - hunspell-ru
  - hunspell-rw
  - hunspell-sc
  - hunspell-se
  - hunspell-shs
  - hunspell-si
  - hunspell-sk
  - hunspell-sl
  - hunspell-smj
  - hunspell-so
  - hunspell-sq
  - hunspell-sr
  - hunspell-ss
  - hunspell-st
  - hunspell-sv
  - hunspell-sw
  - hunspell-ta
  - hunspell-te
  - hunspell-tet
  - hunspell-th
  - hunspell-ti
  - hunspell-tk
  - hunspell-tl
  - hunspell-tn
  - hunspell-tpi
  - hunspell-ts
  - hunspell-uk
  - hunspell-ur
  - hunspell-uz
  - hunspell-ve
  - hunspell-vi
  - hunspell-wa
  - hunspell-xh
  - hunspell-yi
  - hunspell-zu
