document: feedback-pipeline-workload
version: 1
data:
  name: perl-FCGI:0.79 module
  description: Perl client for FCGI web server interface
  maintainer: sst_cs_apps
  labels:
  - eln
  - c9s
  packages:
  - perl-FCGI
