document: feedback-pipeline-workload
version: 1
data:
  name: Performance Tools
  description: Performance Tools and Components
  maintainer: sst_platform_tools

  packages:
  # See dyninst below
  - elfutils
  - elfutils-debuginfod
  - elfutils-debuginfod-client
  - elfutils-debuginfod-client-devel
  - elfutils-default-yama-scope
  - elfutils-devel
  - elfutils-libelf
  - elfutils-libelf-devel
  - elfutils-libs
  - libpfm
  - libpfm-devel
  # See papi below
  - systemtap
  - systemtap-client
  - systemtap-devel
  - systemtap-exporter
  - systemtap-runtime
  - systemtap-runtime-java
  - systemtap-runtime-python3
  - systemtap-runtime-virtguest
  - systemtap-runtime-virthost
  - systemtap-sdt-devel
  - systemtap-server
  - systemtap-testsuite
  - valgrind
  - valgrind-devel

  labels:
  - eln
  - c9s

  # dyninst and papi aren't supported on s390x
  arch_packages:
    aarch64:
    - dyninst
    - dyninst-devel
    - dyninst-doc
    - dyninst-testsuite
    - papi
    - papi-devel
    - papi-libs
    - papi-testsuite
    i686:
    - dyninst
    - dyninst-devel
    - dyninst-doc
    - dyninst-testsuite
    - papi
    - papi-devel
    - papi-libs
    - papi-testsuite
    ppc64le:
    - dyninst
    - dyninst-devel
    - dyninst-doc
    - dyninst-testsuite
    - papi
    - papi-devel
    - papi-libs
    - papi-testsuite
    x86_64:
    - dyninst
    - dyninst-devel
    - dyninst-doc
    - dyninst-testsuite
    - papi
    - papi-devel
    - papi-libs
    - papi-testsuite
