document: feedback-pipeline-workload
version: 1
data:
  name: exfatprogs
  description: Utilities for formatting and repairing exFAT filesystems.
  maintainer: sst_filesystems
  packages:
    - exfatprogs
  labels:
    - eln
    - c9s
    - c10s
