document: feedback-pipeline-workload
version: 1
data:
  name: Scanning Stack - scanning GUI
  description: Graphical application for scanning
  maintainer: sst_cs_infra_services

  packages:
  # tools
  - xsane

  labels:
  - c9s
