document: feedback-pipeline-unwanted
version: 1
data:
  name: arch hw unwanted packages
  description: Unwanted packages no longer headed for hardware enablement
  maintainer: sst_arch_hw

  unwanted_packages:
  - libdv
  - libiec61883
  - fxload

  labels:
  - eln
  - c9s

