document: feedback-pipeline-workload
version: 1
data:
  name: Printing Stack - Printer Applications
  description: Suite of software needed for older printers on Linux
  maintainer: sst_cs_infra_services

  packages:
  - cups-browsed
  - ipp-usb
  - libcupsfilters
  - libppd
  - lprint
  - pappl


  labels:
  - eln
  - c10s
