document: feedback-pipeline-workload
version: 1
data:
  name: Apache Maven
  description: Java project management and project comprehension tool
  maintainer: sst_cs_base_utils
  packages:
    - maven
  labels:
    - c10s
