document: feedback-pipeline-workload
version: 1
data:
  name: Accessibility
  description: Packages to support accessibility in Workstation
  maintainer: sst_desktop_applications
  packages:
    - at-spi2-core
    - liblouis
    - orca
    - speech-dispatcher
  labels:
    - eln
    - c10s
