document: feedback-pipeline-workload
version: 1
data:
  name: SELinux tools
  description: A development tools for SELinux
  maintainer: sst_security_selinux

  packages:
  - policycoreutils-devel
  - policycoreutils-gui
  - policycoreutils-sandbox
  - checkpolicy
  - setools
  - setools-console
  - setools-console-analyses
  - setools-gui
  - selinux-policy-devel
  - udica
  - setroubleshoot
  - netlabel_tools

  labels:
  - eln
  - c9s
