document: feedback-pipeline-workload
version: 1
data:
  name: HW tools
  description: Various tools related to a specific hardware
  maintainer: sst_cs_plumbers

  packages:
  # asamalik: Moving biosdevname to x86 architectures only as it's not available elsewhere
  #- biosdevname
  - ledmon
  - sgpio
  - libatasmart
  
  arch_packages:
    x86_64:
    - biosdevname
    i686:
    - biosdevname

  package_placeholders:
    prefixdevname:
      srpm: prefixdevname
      description: This package is rhel-only NIC naming tool
      buildrequires:
      - rust-toolset
      - git
      - systemd-devel

  labels:
  - eln
