document: feedback-pipeline-workload
version: 1
data:
  name: Hexchat
  description: A graphical IRC client application for Workstation
  maintainer: sst_desktop_applications

  packages:
  - hexchat

  labels:
  - c9s
