document: feedback-pipeline-workload
version: 1
data:
  name: Archiving tools
  description: Archiving and compression tools owned by CS Apps SST
  maintainer: sst_cs_apps

  packages:
  - tar
  - zlib-devel
  - zlib-static

  labels:
  - eln
