document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Text Editor
  description: Text editor for Workstation
  maintainer: sst_display_desktop_foundation
  packages:
    - gnome-text-editor
    - gtksourceview5
    - libspelling
  labels:
    - eln
    - c10s
