document: feedback-pipeline-workload
version: 1
data:
  name: Extra Fonts
  description: Collections of extra packages providing fonts
  maintainer: sst_i18n

  packages:
  - aajohan-comfortaa-fonts
  - adobe-source-code-pro-fonts
  - dejavu-lgc-sans-fonts
  - dejavu-lgc-sans-mono-fonts
  - dejavu-lgc-serif-fonts
  - dejavu-sans-fonts
  - dejavu-sans-mono-fonts
  - dejavu-serif-fonts
  - google-carlito-fonts
  - google-crosextra-caladea-fonts
  - google-roboto-slab-fonts
  - julietaula-montserrat-fonts
  - langpacks-fonts-am
  - langpacks-fonts-ar
  - langpacks-fonts-as
  - langpacks-fonts-ast
  - langpacks-fonts-be
  - langpacks-fonts-bg
  - langpacks-fonts-bn
  - langpacks-fonts-bo
  - langpacks-fonts-br
  - langpacks-fonts-chr
  - langpacks-fonts-dv
  - langpacks-fonts-dz
  - langpacks-fonts-el
  - langpacks-fonts-eo
  - langpacks-fonts-eu
  - langpacks-fonts-fa
  - langpacks-fonts-gu
  - langpacks-fonts-he
  - langpacks-fonts-hi
  - langpacks-fonts-hy
  - langpacks-fonts-ia
  - langpacks-fonts-iu
  - langpacks-fonts-ka
  - langpacks-fonts-km
  - langpacks-fonts-kn
  - langpacks-fonts-ku
  - langpacks-fonts-lo
  - langpacks-fonts-mai
  - langpacks-fonts-ml
  - langpacks-fonts-mr
  - langpacks-fonts-my
  - langpacks-fonts-nb
  - langpacks-fonts-ne
  - langpacks-fonts-nn
  - langpacks-fonts-nr
  - langpacks-fonts-nso
  - langpacks-fonts-or
  - langpacks-fonts-pa
  - langpacks-fonts-ru
  - langpacks-fonts-si
  - langpacks-fonts-ss
  - langpacks-fonts-ta
  - langpacks-fonts-te
  - langpacks-fonts-th
  - langpacks-fonts-tn
  - langpacks-fonts-ts
  - langpacks-fonts-uk
  - langpacks-fonts-ur
  - langpacks-fonts-ve
  - langpacks-fonts-vi
  - langpacks-fonts-xh
  - langpacks-fonts-yi
  - langpacks-fonts-zu
  - lato-fonts
  - liberation-narrow-fonts
  - open-sans-fonts
  - overpass-fonts

  labels:
  - eln
