document: feedback-pipeline-workload
version: 1
data:
  name: Fonts
  description: Collections of packages providing fonts
  maintainer: sst_display_i18n
  packages:
    - default-fonts-am
    - default-fonts-ar
    - default-fonts-as
    - default-fonts-ast
    - default-fonts-be
    - default-fonts-bg
    - default-fonts-bn
    - default-fonts-bo
    - default-fonts-br
    - default-fonts-chr
    - default-fonts-cjk-mono
    - default-fonts-cjk-sans
    - default-fonts-cjk-serif
    - default-fonts-core-emoji
    - default-fonts-core-math
    - default-fonts-core-mono
    - default-fonts-core-sans
    - default-fonts-core-serif
    - default-fonts-dv
    - default-fonts-dz
    - default-fonts-el
    - default-fonts-eo
    - default-fonts-eu
    - default-fonts-fa
    - default-fonts-gu
    - default-fonts-he
    - default-fonts-hi
    - default-fonts-hy
    - default-fonts-ia
    - default-fonts-iu
    - default-fonts-ka
    - default-fonts-km
    - default-fonts-kn
    - default-fonts-ku
    - default-fonts-lo
    - default-fonts-mai
    - default-fonts-ml
    - default-fonts-mr
    - default-fonts-my
    - default-fonts-nb
    - default-fonts-ne
    - default-fonts-nn
    - default-fonts-nr
    - default-fonts-nso
    - default-fonts-or
    - default-fonts-other-mono
    - default-fonts-other-sans
    - default-fonts-other-serif
    - default-fonts-pa
    - default-fonts-ru
    - default-fonts-si
    - default-fonts-ss
    - default-fonts-ta
    - default-fonts-te
    - default-fonts-th
    - default-fonts-tn
    - default-fonts-ts
    - default-fonts-uk
    - default-fonts-ur
    - default-fonts-ve
    - default-fonts-vi
    - default-fonts-xh
    - default-fonts-yi
    - default-fonts-zu
    - liberation-mono-fonts
    - liberation-sans-fonts
    - liberation-serif-fonts
    - pt-sans-fonts
    - redhat-display-fonts
    - redhat-mono-fonts
    - redhat-text-fonts
  labels:
    - eln
    - c10s
