document: feedback-pipeline-workload
version: 1
data:
  name: Networking Tools - unwanteds
  description: >
    Unwanted packages related to network configuration and troubleshooting.
  maintainer: sst_networking

  unwanted_packages:
  - dropwatch

  labels:
  - eln
  - c9s
