document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted ELN packages
  description: Various unwanted packages. See comments in the config for more detail.
  maintainer: bakery
  labels:
    - eln
    - c9s
    - c10s
  ###  Unwanted packages in ELN  ###
  #
  # Before using this list, please consider your own exclusion list
  # such as "sst_cs_software_management-unwanted.yaml" as an example.
  # This helps track ownership better, as you can set the maintainer
  # field to represent you or your team.
  #
  # When adding a package to the following list, please include your
  # name and the reason of why are you listing it.
  unwanted_packages:
    # Josh Boyer: Drop R from ELN to see what the fallout is.
    - R
    # Enterprise doesn't support btrfs
    - btrfs-progs
    - btrfs-progs-devel
    # Josh Boyer: Mono hasn't been carried in RHEL and there are
    # no plans to add it. Exclude it from ELN for now.
    - mono-core
    - mono-devel
    - monodoc
    - monodoc-devel
    # Troy Dawson
    - xen
    - xen-devel
    - xen-hypervisor
    - xen-libs
    - xen-licenses
    - xen-ocaml
    - xen-ocaml-devel
    - xen-runtime
    - xen-doc
    # VÃ­t Ondruch: rubypick is not needed and there is %bcond_without
    # to disable it
    - rubypick
    # Dalibor Pospisil:
    # beakerlib was just a build dependency of chkconfig
    # beakerlib must not be present in the customer facing compose / repos
    # it might be part of buildroot only if really needed
    - beakerlib
    # John Feeney:
    # old firewire packages
    - libdv
    - libiec61883
    #Jaroslav Kysela:
    # It's sound font loader for (really) old Creative hardware. The recent hardware does not require it.
    - fxload
